### ISSUE TITLE
Empty structure.

### ISSUE THREAD

**Issue by RitsmG** [OFFLINE-GmbH/oc-boxes-support#102]
Hello.

Since the latest version v3.3.20. The structure part is empty when a page is selected that has boxes in it.

![Screenshot 2024-02-02 at 14 49 48](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/83651566/3cb7a83e-e991-43a4-9e3a-67cf2929b872)

**Boxes Version**
v3.3.20

**Comment by tobias-kuendig** [comment]
Hi @RitsmG 

Thank you for this report! This was indeed a bug introduced in the latest version. It is fixed in v3.3.21
