### ISSUE TITLE
Exclude Specific Layouts from Layout Dropdown / Only Include Specific Layouts

### ISSUE THREAD

**Issue by sqwk** [OFFLINE-GmbH/oc-boxes-support#107]
There is a context for nested boxes. Is it possible to also filter the CMS layout list that boxes uses to not include every single layout that exists? Static Pages achieves this by not including the `staticPages` component — Boxes simply grabs every available CMS page.

**Comment by tobias-kuendig** [comment]
@sqwk you can use the `offline.boxes.filterLayouts` Event starting from version 3.5.2.

https://docs.boxes.offline.ch/reference/events.html#offline-boxes-filterlayouts
