### ISSUE TITLE
Receive Error on page creation (after theme change)

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#11]
**Describe the bug**
With a fresh frontend theme activated, I am trying to create a new page within the Boxes plugin, and I receive the error ""Cannot resolve target node." on line 922 of /home/xxxxxx/public_html/vendor/october/rain/src/Database/Traits/NestedTree.php"

I am using  OCMS build 3.0.70 and Boxes version 2.0.55

**To Reproduce**
1. Install the boxes plugin
2. Activate a new frontend theme
3. Go to the Content menu in boxes
4. Click "Create Page" - add name
5. Error shows on saving - cannot proceed.

**Additional context**
I am attempting to use the plugin on the Octobercms Demo site. It seems to work fine on the demo frontend theme that was installed at the time I installed the boxes plugin, this error only occurs when I activate a new frontend theme. I thought the theme itself might be the issue so I duplicated the original demo theme and tried that duplicate as a new theme, and the error still occurred.

**Comment by roojai** [comment]
Quick update:

I found I could get around this issue by uninstalling Boxes plugin and then reinstalling it while my frontend theme was activated. 

This is a repeatable issue, every time I try to use a frontend theme that was not active at the time of installation of the plugin there is an error. So short-term solution is to only install it after you have activated the theme you intend to use.

**Comment by tobias-kuendig** [comment]
Thank you for the report @roojai! I will take a look at this.

**Comment by tobias-kuendig** [comment]
This is fixed in v2.0.62! Let me know if the issue persists.
