### ISSUE TITLE
Nested Tree Structure: any interaction with a nested component beyond 2 levels is not functioning as expected

### ISSUE THREAD

**Issue by KiryaAfimin** [OFFLINE-GmbH/oc-boxes-support#110]
**Describe the bug**
Any interaction with a nested component beyond 2 levels is not functioning as expected. Sorting, clicking on buttons, and dragging components from one level to a nested level do not register changes. However, the functionality works correctly in reverse. If a component is dragged from a nested level to the first level, everything works as expected.

**Boxes Version**
v3.3.21

**To Reproduce**
1. Create a couple of nested components.
2. Add these components to the Nested Tree Structure.
3. Attempt to drag one component into another nested component.
4. Try clicking on the "Add Box" button within the nested component.
5. Save the changes.
6. Refresh the page.

**Screenshots**
![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/21101743/4ff45f9f-e8f0-4ce1-8bd9-77130227507c)

**Comment by tobias-kuendig** [comment]
Thank you for this report, @KiryaAfimin. The "Add Box" action is fixed in v3.4.3. The sorting will need some further work.

**Comment by elisandroesp** [comment]
+1 for this fix.
Currently you can drag an item OUT of a nested component, but not INTO the component.
Imagine I have a 'carousel' or 'columns' component that I want to move items TO them, but it's impossible now.

**Comment by anastasiauz** [comment]
+1! There are some problems with reordering which works in the central preview area but doesn't if you try to reorder in the left bar by dragging. Likely it's the same issue as described in this bug report - after 2 level of nesting things start to get weird. Very much need a fix as we are planning to use Boxes in many projects

**Comment by tobias-kuendig** [comment]
Thanks everyone, please give v3.6.4 a try. The sorting is completely redone in that version and should work as expected now.
