### ISSUE TITLE
Copy to site missing sites that are 'editable' but nog yet active

### ISSUE THREAD

**Issue by gldrenthe89** [OFFLINE-GmbH/oc-boxes-support#114]
**Describe the bug**
Since the update of v3.5 you now have to copy sites using the copy to site button in de editor. But the list is missing sites that are not yet fully enabled (thus not yet live) but are enabled for admin panel (Option: Enabled in the Admin Panel). These sites are in the site switcher available. But are not listed in the copy to site select input. Can you please fix this to show also those websites? 

**Boxes Version**
v3.5.8

**Screenshots**
![Screenshot 2024-04-03 at 13 43 42](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/56250338/14f60376-7e01-49d9-b820-f9483cb59f27)
![Screenshot 2024-04-03 at 13 43 57](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/56250338/cd73b07e-caa1-487a-9755-d2a0b87b5e45)
![Screenshot 2024-04-03 at 13 44 06](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/56250338/d41079fc-e0a3-4271-8999-bf01dede6387)

**Comment by tobias-kuendig** [comment]
@gldrenthe89, thank you for this feedback. Please give v3.5.9 a try, all sites are now available to select.

**Comment by gldrenthe89** [comment]
> @gldrenthe89, thank you for this feedback. Please give v3.5.9 a try, all sites are now available to select.

Thanks for the quick fix. We have implemented is and indeed the list is now fully shown. Many thanks.
