### ISSUE TITLE
Extend Page backend fields with a repeater type cause an error

### ISSUE THREAD

**Issue by anastasiauz** [OFFLINE-GmbH/oc-boxes-support#118]
**Describe the bug**
Using 'backend.form.extendFields' Event I extended the Page model with a repeater field. When trying to add a new item, an error is thrown: Attempt to modify property "config" on null in [.../plugins/offline/boxes/models/Page.php:200]

**Boxes Version**
latest, paid

If add an IF like this it works. If this edit is safe please add it in the next release, otherwise let us know if we can use repeater while extending page form fields.

```php
    if ($widget->model->exists || !$holder->get('template')?->options()) {
                if ($holder->get('template')) {
                    $holder->get('template')->config['hidden'] = true;
                }
            }
```

**Comment by anastasiauz** [comment]
After more testing I need to add that only first item of repeater fields array is saved. So likely now we cannot use repeater for Page. Will find another way but would have been nice if it worked

**Comment by tobias-kuendig** [comment]
Thank you for this report. The form extension event was triggered for the nested repeater form as well. Starting from v3.6.2 this is no longer a problem.

You can use the following code to add a custom repeater to the Page form (use the [`custom_config` field](https://docs.boxes.offline.ch/use-cases/page-specific-data.html)):

```php
        // Provider.php -> boot()
        \Event::listen('backend.form.extendFields', function ($widget) {
            if (!$widget->model instanceof \OFFLINE\Boxes\Models\Page) {
                return;
            }

            $widget->addTabFields([
                'custom_config[your_repeater]' => [
                    'tab' => 'Your Tab',
                    'type' => 'repeater',
                    'span' => 'full',
                    'form' => [
                        'fields' => [
                            'some_field' => [
                                'label' => 'Some Field',
                                'type' => 'text',
                                'span' => 'full',
                            ],
                        ]
                    ]
                ],
            ]);
        });
```

**Comment by anastasiauz** [comment]
Hi! I tested that on my end and can confirm - repeater works. Thank you!
