### ISSUE TITLE
Unable to create pages

### ISSUE THREAD

**Issue by RitsmG** [OFFLINE-GmbH/oc-boxes-support#120]
Since updating to v3.6.4 we are unable to create new pages. 

When revisions are disabled we do not see updates on the frontend after making changes. The only way we are able to see the changes we make is going through boxes to the preview which opens a draft site even though revisions are disabled.

**Boxes Version**
v3.6.4

**Comment by tobias-kuendig** [comment]
@RitsmG thank you for this bug report. The "Create new page" action was actually missing in the latest version due to a refactoring. v3.6.6 fixes this.

As for the second part of your report: I am unable to reproduce this issue. If i disable the revisions system, the frontend always serves the page that has a `published_state` of `draft` in the database.

The `HasRevisions` trait contains a `scopeCurrentByPublishingState` method that defaults the query to the `draft` state, if the revisions feature is disabled.

**Comment by gldrenthe89** [comment]
> @RitsmG thank you for this bug report. The "Create new page" action was actually missing in the latest version due to a refactoring. v3.6.6 fixes this.
> 
> As for the second part of your report: I am unable to reproduce this issue. If i disable the revisions system, the frontend always serves the page that has a `published_state` of `draft` in the database.
> 
> The `HasRevisions` trait contains a `scopeCurrentByPublishingState` method that defaults the query to the `draft` state, if the revisions feature is disabled.

Hi @tobias-kuendig would that trait be the issue in this case? we are getting empyt pages (possibly old drafts???) after turning off revisions on a site that used revisions. Shouldnt be the latest version (published) be used? and not a draft?

If needed i can send a sql export of the tables?

**Comment by tobias-kuendig** [comment]
> Shouldnt be the latest version (published) be used? and not a draft?

The latest `draft` is always the working copy. Publishing a page creates a new copy of it. When you turn off the revisions feature after you had pages with revisions, only the latest draft will be visible on the site, since this is always the original page record in the database.

**Comment by gldrenthe89** [comment]
@tobias-kuendig i have send you an email with the SQL tables

**Comment by tobias-kuendig** [comment]
@gldrenthe89 thank you! I'm still trying to reproduce the issue. I do the following, maybe you can confirm that this works or tell me where you receive a different output:

1. I have revisions disabled in Boxes' backend settings.
2. In a private browser window, I open the /support page
3. In another window, I change the title/meta title of this page in the Boxes Editor. When I reload the page in the private window, I see the change reflected.
4. I add a new Box to that page, this change is reflected in the private window as well.
5. I add a `dd($page)` before this line: https://github.com/OFFLINE-GmbH/oc-boxes-free-plugin/blob/1ca8a21d4386a51f9f8a49c5813879fd9c951cfb/classes/cms/Controller.php#L58 
6. When I reload the page, I see that page ID 7 is loaded (which is the draft, so in case of the disabled revisions feature, this is the correct page to load).

**Comment by RitsmG** [comment]
Good morning @tobias-kuendig,

I tried reproducing the issues with the method you used.

When on the page "/prijzen" with revisions disabled and the `dd($page);` on line 57 in the controller.php file. I get the resulting page with id number "18". 
`  #original: array:32 [▼
    "id" => 18
    "name" => "prijzen"
    "slug" => "prijzen"
    "url" => "/prijzen"
    "canonical_url" => ""
    "layout" => "default"
    "theme" => "dans-basis"
    "meta_title" => ""
    "meta_description" => ""
    "meta_robots" => ""
    "og_title" => ""
    "og_description" => ""
    "og_type" => "website"
    "is_hidden" => 0
    "category_id" => null
    "parent_id" => null
    "nest_left" => 7
    "nest_right" => 8
    "nest_depth" => 0
    "custom_config" => null
    "created_at" => "2024-04-04 16:43:57"
    "updated_at" => "2024-04-11 08:52:20"
    "updated_by" => 3
    "site_id" => 1
    "site_root_id" => 9
    "origin_page_id" => 9
    "published_state" => "outdated"
    "published_at" => "2024-04-04 16:43:57"
    "published_by" => 3
    "has_pending_changes" => 0
    "version" => 1
    "is_hidden_in_navigation" => 0
  ]`

When enabling the revisions in the backend and refreshing the page, I get the page ID "9" instead of "90" as it should be according to the "published_state" column in the database. Though then the page does load for me.
`  #original: array:32 [▼
    "id" => 9
    "name" => "Prijzen"
    "slug" => "prijzen"
    "url" => "/prijzen"
    "canonical_url" => ""
    "layout" => "hero"
    "theme" => "dans-basis"
    "meta_title" => ""
    "meta_description" => ""
    "meta_robots" => ""
    "og_title" => ""
    "og_description" => ""
    "og_type" => "website"
    "is_hidden" => 0
    "category_id" => null
    "parent_id" => null
    "nest_left" => 11
    "nest_right" => 12
    "nest_depth" => 0
    "custom_config" => null
    "created_at" => "2024-04-04 15:24:21"
    "updated_at" => "2024-04-18 15:30:11"
    "updated_by" => 2
    "site_id" => 1
    "site_root_id" => 9
    "origin_page_id" => 9
    "published_state" => "draft"
    "published_at" => null
    "published_by" => 4
    "has_pending_changes" => 1
    "version" => null
    "is_hidden_in_navigation" => 0
  ]`

**Comment by tobias-kuendig** [comment]
Ah, I was able to reproduce it with that one page! Please try v3.6.7 and see if the problem is solved there.

**Comment by RitsmG** [comment]
The update appears to have fixed the issue where the content did not load on the page when revisions are disabled. Though the DD output still shows the wrong database row/id.

**Comment by tobias-kuendig** [comment]
Wrong in what context? You have revisions enabled and it does not show the page with the `published` status? Or do you have revisions disabled and it does not show the page with the `draft` status?

**Comment by RitsmG** [comment]
I did a little test to see which data was shown and it seems it is showing the correct data.

**Comment by tobias-kuendig** [comment]
Alright! Thank you very much for your effort here. Let me know if you notice anything wrong.
