### ISSUE TITLE
Multisite export function only exports site_id 1

### ISSUE THREAD

**Issue by raumfisch** [OFFLINE-GmbH/oc-boxes-support#123]
**Describe the bug**
We are developing a site using the October Multisite function to provide a multilanguage function. For our deployment, we use the 'artisan boxes:export' command to store the configuration in git. 
In the exported yaml files, we find only the configuration for 'site_id: 1', the other sites are left out. 
  
**Boxes Version**
v3.6.10

**Additional context**

Is there anything we are missing, to export the configuration for the other sites aswell? I can not find anything in the documentation or the help context of the artisan command.

**Comment by tobias-kuendig** [comment]
@raumfisch the import/export feature has been removed from the official feature set for some time now. Maybe we will bring it back in the future, but with the addition of multisite support and the revisions system, everything became a bit too complicated to ship in a stable way.

**Comment by raumfisch** [comment]
What is the recommended way to deploy changes in a staging environment? Does this make it necessary to import/export the databases, or parts of it?

**Comment by tobias-kuendig** [comment]
That is correct, you would have to deploy the changes the same way you would deploy any other data: Export and import the `offline_boxes_*` tables as well as the `system_files` table (or just the related records in it).

**Comment by raumfisch** [comment]
Ok, than i had a missunderstanding here. I was thinking that parts of the configuration is considered as structure that can be stored in git, using the import and export functionality.
Of course, data should not be stored in version control.
