### ISSUE TITLE
Absolute Filepaths in exported yaml configuration

### ISSUE THREAD

**Issue by raumfisch** [OFFLINE-GmbH/oc-boxes-support#124]
**Describe the bug**
I am using the "artisan boxes:export" command to save the configuration in git. In the exported yaml configuration, i am seeing absolute filepaths in the attached images (see attached screenshot)

The filepath contains the home-directory of the computer where the export is made. This way, it is not possible to sucessfully import the attachment on another system. 

Also, i am missing out the attached file in the export.

**Boxes Version**
v3.6.10

**Screenshots**
![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/5468395/a27fd511-bd57-4827-8a09-40df51969b1f)

**Additional context**
I am using php8.3 on latest OSX.

**Comment by tobias-kuendig** [comment]
@raumfisch the import/export feature has been removed from the official feature set for some time now. Maybe we will bring it back in the future, but with the addition of multisite support and the revisions system, everything became a bit too complicated to ship in a stable way.
