### ISSUE TITLE
Multisite menu loses reference to Boxes page when the linked pages have different URLS

### ISSUE THREAD

**Issue by caswolters** [OFFLINE-GmbH/oc-boxes-support#125]
**Describe the bug**
We have a multisite website with the boxes plugin. We build the pages using boxes.
After creating all the pages we started on the menu for all sites (languages).

When we create the menu for multisite 1 everything is fine; when we move on to multisite 2 and link the same page but in a different language to a menu item, the menu item in multisite 1 is lost.

This does not occur when the pages share the same URL. Since we have multiple languages the URL is different (for SEO purposes).

**Boxes Version**
v3.6.10

**To Reproduce**
See discription of the bug

Screenshot of a menu item that has lost the reference to the page.
![Screenshot 2024-05-06 at 21 11 30](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/5374212/6a9fd6e8-a8cb-454e-9e32-02da25a1d4af)

**Comment by tobias-kuendig** [comment]
@caswolters thank you for this report! Is the reference only lost in the backend (Unnamed menu item) or does it not work in the frontend as well?

**Comment by caswolters** [comment]
@tobias-kuendig It is lost in frontend aswel.

**Comment by tobias-kuendig** [comment]
Thank you @caswolters! Please give v3.6.13 a try and see if things are working for you.
