### ISSUE TITLE
Restrict some boxes to specific pages

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#13]
Hello,

It would be useful to be able to restrict the usage of some boxes to specific pages, by adding en option on the box config yaml file where you put a list of pages codes : 

It would be probably a good idea to develop an including and excluding logic, something like that : 

    includedPages:
          - page-1
          - page-2
          - page-2
     excludedPages:
          - page-4

If includesPages is filled, the box is available only for those pages, if exludedPages is filled, the box is available everywhere except for the excluded pages

If that options are not filled at all, the box is available everywhere, like today

What do you think about this feature ?

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Great idea! We had this implemented once for nested Boxes, where you could define what Boxes are available in the context of a certain parent. 

I will put this on the roadmap and see if we can find an implementation that covers all the current use-cases.

**Comment by PubliAlex** [comment]
Small bump about this feature.

I'm actually using box in 2 different context : 
- The "standard" box backend interface to build my whole pages
- As a form widget in tailor to manage the content of my blog posts

It works great, the the possibility to define another layout using the "previewLayout"

Now I would like to be able to define different set of boxes depending on where I am. My blog posts will have it's own set of boxes and my page templating system will have another set of boxes.

If you work on a way to be able to restrict boxes to specific page, it would also be useful to be able to restrict boxes to a specific context (maybe being able to specify a list of models or tailor uuid or something like that ?)

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
We have discussed this feature shortly in the team and have two key take aways:

* We do _not_ think that defining what pages a partial is valid for is the way to go. Partials are currently completely independent of your content. If the partial defines for what pages it is valid for, a hard dependency on your website context is created.
* We do think a better way to go is to limit certain partials to specific CMS layouts or, as you proposed, to a certain context, but the context should still be generic enough so the partials could be re-used across projects.

Would the layout option be enough for your use-case?

**Comment by PubliAlex** [comment]
Hello Tobias, thank you for your feedback.

So you plan to add layout option to boxes configuration yaml file like that ? : 

    layouts:
    - default
    - layout1
    - layout2
    - etc....

If yes, I think it can do the job. Maybe not ideal because I can imagine some uses cases where pages having the same layout can need to have different set of boxes, but if that's the case, we just have to clone the layout so it's a quite good solution to me.

**Comment by PubliAlex** [comment]
Hello @tobias-kuendig ,

Do you have a roadmap for this feature ? Do you plan to implement it before the end of the year ? Cause I'm working on several projects that would need it

Thank you

**Comment by tobias-kuendig** [comment]
I will prioritize it for the coming days. We probably will opt for a "context" option that allows you to include certain partials in certain situations only.

**Comment by PubliAlex** [comment]
ah perfect, my main goal would be to separate the list of available boxes if I'm on a boxes page or if I'm on a tailor model

**Comment by tobias-kuendig** [comment]
An initial version of this feature has been released in v2.1.4. Let me know if this fits your use-case.

Docs: https://docs.boxes.offline.ch/use-cases/usage-in-plugins.html#contexts

**Comment by EricNiedergang** [comment]
Hello @tobias-kuendig the context feature seems to do the job when I'm using boxes as a field in a custom model.

However, as I created some special boxes for that model, I don't want to see that boxes when I'm using the standard boxes pages. I'm not sur it's possible in that direction.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
You should be able to solve this by adding a special context to your "custom model partials":

```yaml
handle: only-for-custom-model
contexts:
- custom-model
```

If the `default` context is not listed under `contexts`, the partial will not be visible when editing normal pages but only when editing the custom model content.

If the partial still shows up, that would be a bug.

See https://docs.boxes.offline.ch/reference/schema.html#contexts
