### ISSUE TITLE
AJAX handler 'onRenderBoxForm' was not found into modal

### ISSUE THREAD

**Issue by lorenzoantei** [OFFLINE-GmbH/oc-boxes-support#130]
Hello. I am trying to integrate boxes into a field within a modal. I can see the field and add a box. However, when I select a box, I get the error: "AJAX handler 'onRenderBoxForm' was not found." 

**Boxes Version**
v3.6.14

**To Reproduce**
1. add a Pivot model
2. create boxes field
3. create an entry
4. open modal

To display the box selection popup, I have added the following classes: (CSS classes):

```
#Form-relationStagesManagePivotForm-field-Stage-boxes_contents-group {
    height: 100vh;
}

.popup-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 9999; /* Un valore molto alto per assicurare che sia sopra tutto */
    background: rgba(0, 0, 0, 0.5); /* Opzionale: aggiunge un'ombra scura di sfondo */
}

.popup-body-host {
    position: relative;
    z-index: 10000; /* Un valore ancora più alto per assicurare che il contenuto del popup sia sopra l'overlay */
}

```

![Schermata_20240614_212427](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/58749463/f6acc8bc-1b89-4864-9648-74e40ee738a1)

**Comment by tobias-kuendig** [comment]
@lorenzoantei rendering the editor in a popup is not supported. 

This essentially results in a nested relationship, which October does not support without manual work. In your case, the editor is registered and rendered in the RelationController. It only works if it is registered in the primary FormController. 

There are even some official tutorials on this topic, but I fear that getting the Editor to work in the popup is a bit more complicated.

https://octobercms.com/support/article/ob-21

**Comment by lorenzoantei** [comment]
Thank you @tobias-kuendig . I 'solved' it by adding the morphOne declaration to the parent model and putting a hidden 'boxes' field on it.
