### ISSUE TITLE
Disabled Boxes Still Show up on Front End

### ISSUE THREAD

**Issue by sqwk** [OFFLINE-GmbH/oc-boxes-support#132]
When unchecking the "Is Enabled" switch in the backend, the box still shows up on the front end.

Boxes have to be wrapped in an if statement to hide them on the front end:

```
{% if box.is_enabled or context.isEditor %}
    ...
{% endif %}
```

**Comment by patrick-durrer** [comment]
Boxes that are deactivated via the toggle are still displayed for all users that are logged in to the backend (this allows administrators to preview the content). Therefore, my question is: Is the deactivated content also displayed when you open the page without a backend session (for example, in an incognito window)?

**Comment by sqwk** [comment]
Ah, I overlooked the logged-in part. Thanks for clarifying.
