### ISSUE TITLE
Improve block selection popup

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#135]
Hello,

It would be great of boxes would take some inspiration from [easyblocks](https://easyblocks-demo.vercel.app/) concerning the block selection popup.

Try to add a block with the easyblocks demo. IMO, the easyblocks UI here is better to what offline boxes provide in terms of display, categorization etc...

**Comment by tobias-kuendig** [comment]
@PubliAlex thank you for this input. The popup can certainly be imporived. I'll add this to the backlog. Please be aware that it is of low priority to us at the moment.

**Comment by PubliAlex** [comment]
@tobias-kuendig Thank you, by the way, easyblocks have a very nice UX where you can take some inspiration

**Comment by tobias-kuendig** [comment]
The popup got a little facelift in v3.6.21
