### ISSUE TITLE
Error: Call to undefined function OFFLINE\Boxes\Classes\Partial\fake()

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#136]
**Describe the bug**
Hello, I tried to test the preview feature with fake data, here is a simple box.

    name: Texte
    handle: text
    section: Basique
    form:
        fields:
            text:
                label: Texte
                type: richeditor
                example:
                    fake: paragraphs
                    args: [2]

But it generate a error 500 in JS debug panel, and when I go to the October CMS event log, I get this : 

Error: Call to undefined function OFFLINE\Boxes\Classes\Partial\fake() in [/plugins/offline/boxes/classes/partial/Partial.php:186](javascript:)

**Boxes Version**
v3.6.14

**Additional context**
If I put a single string as example, it works, the problem is with fake only.

**Comment by tobias-kuendig** [comment]
@PubliAlex please give v3.6.15 a go. If you installed the composer packages using the `--no-dev` flag, faker will be unavailable. I have fixed this in the latest Boxes version.
