### ISSUE TITLE
You can move a box to a forbidden context

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#140]
**Describe the bug**
When you use nested boxes, there is a context option to limit the available boxes as child of the current box. It works when you click the add box button, but you can add a box that is outside of the context if you drag & drop it using the navigation panel on the left sidebar.

**Boxes Version**
v3.6.15

**Screenshots**
You can see in the video below that the "Text" box is the only available children of "Row" bow. When I add the children, it works. But I can add an "Image" box type somewhere else, then drag & drop it to become a child of Row, which should be impossible.

https://www.loom.com/share/ba59f1dd5af449318625268e14083ba8

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you @PubliAlex for the detailed report! The contexts are now respected when moving Boxes in the editor. v3.6.16 contains the updated logic.

**Comment by PubliAlex** [comment]
@tobias-kuendig Your fix works great except one thing : 

When the parent box don't have child yet, you can't drag & drop another box inside it, even if context allow it.

If the parent box already have some boxes in it, it works correctly.

**Comment by tobias-kuendig** [comment]
Thanks, this is fixed in v3.6.17.
