### ISSUE TITLE
Add clone box button in the navigation panel (left sidebar)

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#142]
Hello,

It would be useful to add a clone button in the navigation panel because when you use the nested box features, it can be hard sometime to select the box you want (the parent box for example). So adding duplicate box option in the left sidebar would make life easier.

![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/55833027/a01607df-ddf0-428b-a730-399fda24a15d)

Thank you

**Comment by tobias-kuendig** [comment]
Thank you for the feedback @PubliAlex, this is available in v3.6.20
