### ISSUE TITLE
Can't use multisites into a custom's plugin field.

### ISSUE THREAD

**Issue by lorenzoantei** [OFFLINE-GmbH/oc-boxes-support#144]
**Describe the bug**
I've added a boxes field to my plugin's model and included the field in the $translatable array. However, when switching the language using the backend dropdown, the field's content does not change. I'm trying to implement translation for different languages.

**Boxes Version**
v3.6.10

(edit)
**Code**
```
public $implement = ["@RainLab.Translate.Behaviors.TranslatableModel"];
public $translatable = [
        'boxes_contents',
        'sections', // a box
    ];
public $morphOne = [
        'boxes_contents' => [    // Any name you want
            \OFFLINE\Boxes\Models\Content::class,
            'name' => 'content' // Has to be called 'content'
        ]
    ];
```

**Comment by tobias-kuendig** [comment]
What version of October/Translate are you using? The suggested method is to use the Multisite feature and no longer rely on the `$translatable` property.

**Comment by lorenzoantei** [comment]
> What version of October/Translate are you using? The suggested method is to use the Multisite feature and no longer rely on the `$translatable` property.

OctoberCms 3.6.10
Rainlab.Translate 2.2.8

Into the preview I have a theme with this:
```
{% for site in sitePicker.sites %}
	{% if this.site.code != site.code %}
	<li class="">
	    <a class="" href="{{ site.url }}">
		{{ site.code }}
	    </a>&nbsp;
	</li>
	{% endif %}
{% endfor %}

```
I can see only the default site. If I tried to switch language, it still reopen the same one. Outside it works.

**Comment by lorenzoantei** [comment]
In the preview of boxes, the site always remains in the primary version whether I try to change the language from the multisite switch or from the switch in the theme within the preview.

**Comment by tobias-kuendig** [comment]
Does your custom model implement the `Multisite` trait?

https://docs.octobercms.com/3.x/extend/database/traits.html#multisite

You need this to get a new model instance per site. For each instance, you will then get a new Boxes Content relation.

**Comment by lorenzoantei** [comment]
> Does your custom model implement the `Multisite` trait?
> 
> https://docs.octobercms.com/3.x/extend/database/traits.html#multisite
> 
> You need this to get a new model instance per site. For each instance, you will then get a new Boxes Content relation.

Do you mean to add this into Model?

```
use \October\Rain\Database\Traits\Multisite;
protected $propagatable = ['boxes_contents'];
```

If I do it, I get this error: 
_"The $propagatable property in [MYMODEL] must be an array to use the Multisite trait." on line 49 of xxyz/vendor/october/rain/src/Database/Traits/Multisite.php_

**Comment by tobias-kuendig** [comment]
This is correct, the error has nothing to do with Boxes but your custom code, make sure to check for syntax errors.

If you want to have a separate `boxes_contents` per Site you have to remove it from the array anyways. `propagatable` means that October makes the data for each Site the same.

```php
class YourModel extends Model
{
    use \October\Rain\Database\Traits\Multisite;

    protected $propagatable = [];

    public $morphOne = [
        'boxes_contents' => [    
            \OFFLINE\Boxes\Models\Content::class,
            'name' => 'content' 
        ]
    ];
}
```

**Comment by lorenzoantei** [comment]
> This is correct, the error has nothing to do with Boxes but your custom code, make sure to check for syntax errors.
> 
> If you want to have a separate `boxes_contents` per Site you have to remove it from the array anyways. `propagatable` means that October makes the data for each Site the same.
> 
> ```
> class YourModel extends Model
> {
>     use \October\Rain\Database\Traits\Multisite;
> 
>     protected $propagatable = [];
> 
>     public $morphOne = [
>         'boxes_contents' => [    
>             \OFFLINE\Boxes\Models\Content::class,
>             'name' => 'content' 
>         ]
>     ];
> }
> ```

Thanks it works! Now I choose language by backend dropdown. If the record for the other site does not exist then it creates it for me by duplicating the data from the previous one.
