### ISSUE TITLE
Boxes plugin sometimes shows duplicates of the boxes in the backend after saving

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#15]
**Describe the bug**
When saving a page a duplicate output of a box is displayed in the backend. This duplicate seems to be only a visual issue - the frontend will only show the correct number of boxes. If you delete the duplicate box then both it and the original box are deleted (so they must be the same box as far as the data is concerned. 

**To Reproduce**
This does not ALWAYS happen and I am still trying to find the exact criteria. However it is happening quite a bit. 
1. Create a new page
2. Add a box
3. Add a second box
4. Refresh the Content area and open the new page. 
5. With one of the previously created boxes highlighted (as if to edit), click save
6. A duplicate box appears (sometimes)

I am using a repeater in the duplicated boxes - perhaps a contributing cause?

**Screenshots**
Video of issue:
https://youtu.be/tqJvzhHXm4Y

**Comment by tobias-kuendig** [comment]
Thank you very much for this detailed bug report! I'm looking into it.

**Comment by tobias-kuendig** [comment]
@roojai I'm having a hard time recreating this issue and no one from our team has noticed it as well.

How often does the issue appear? Is it just with a specific Box or with all of them?

**Comment by roojai** [comment]
@tobias-kuendig Thanks very much for the follow-up. I had a very good look at when this happens, and managed to work out the cause! 

One of my box partials had an extra closing div (error in coding). This causes the box to duplicate itself for some reason. I have fixed my code and the issue no longer occurs.

**Comment by tobias-kuendig** [comment]
Glad we figured that one out!  :grinning:  Thank you for the feedback!
