### ISSUE TITLE
Exception while copy child page to another site

### ISSUE THREAD

**Issue by m49n** [OFFLINE-GmbH/oc-boxes-support#150]
last version of plugin
if you try to copy a child page when there is no parent page on another site, we will get an error
![image](https://github.com/user-attachments/assets/e55ed440-a6d2-48a9-8490-baf254e1bdbf)
![image](https://github.com/user-attachments/assets/50ade6c2-c852-4ec1-9d97-eaa79223f5a1)

I think it's worth adding the ability to copy pages together with all nesting

**Comment by tobias-kuendig** [comment]
This is a tricky one, I will have to look into this, thank you for the report @m49n!

**Comment by tobias-kuendig** [comment]
This is fixed in v3.6.26
