### ISSUE TITLE
Page is not updated when I save a box

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-boxes-support#154]
**Describe the bug**
The site preview is not refreshed when you add a new box to the page and it throw an error in the console : 

![image](https://github.com/user-attachments/assets/b52f04fa-8022-4b57-86c6-9a5db1a447c2)

If I click on the offline.boxes.editor.js file referenced in the error log, it reference the following line (in pink)

![image](https://github.com/user-attachments/assets/7c991951-d20d-4817-a15f-e8a53f27c649)

If I refresh the page manually by using the refresh icon of the browser, the box correctly appears.

See loom below : 
https://www.loom.com/share/000101378309464994a69c480827d3c8

**Boxes Version**
v3.6.29

**October Version**
v3.7.1

**To Reproduce**
See loom below : 
https://www.loom.com/share/000101378309464994a69c480827d3c8

**Code**
Here is my box yaml : 

    name: Titre
    handle: title
    section: Common
    form:
        fields:
            title:
                label: Titre
                type: text
            tag:
                label: Tag
                type: balloon-selector
                default: h2
                options:
                    h2: H2
                    h3: H3
                    h4: H4
                    h5: H5
                    h6: H6

Here is my box HTML : 

    <div class="py-lg">
        <div class="container">
            <div class="grid grid-12">
                <div class="start-3 span-8">
                    <{{ box.tag }}>
                        {{ box.title }}
                    </{{ box.tag }}>
                </div>
            </div>
        </div>
    </div>

**Additional context**
Problem appears after a fresh install of boxes on a just updated October 3.7.1.

NB : When I delete a box, the page is correctly refreshed. Problem appears only when I try to **create a new box** or I **reorder existing boxes**.

**Comment by tobias-kuendig** [comment]
![image](https://github.com/user-attachments/assets/911e3a6c-141d-41ab-bd21-102b7437ca8c)


Looking at this screenshot, it looks like the request returns an error message. It should return JSON. Can you look at the network tab and post the full response? Also check the system.log, maybe an exception is logged there.

**Comment by Zmove** [comment]
I'm not sure what do you want about the post full response. Here is when I get when I click on the error : 

    <!DOCTYPE html>
    <html prefix="og: http://ogp.me/ns#">
    <head>
        <link rel="stylesheet" href="/plugins/offline/boxes/assets/css/offline.boxes.editor.css?v=6" />
        <link href="/combine/2f6c3321e31309b0248c134cfa51b9c9-1728935838.css" rel="stylesheet" />
            <script src="/plugins/offline/boxes/assets/js/offline.boxes.editor.js?v=6"></script>
    </head>
    
    <body>
        <div id="page">
            <main id="main">
                <div class="oc-boxes-editor">
        <div class="oc-boxes-editor__render">
            
        </div>
    </div>
    
    <div class="oc-boxes-wrapper">
        <a href="#" class="oc-boxes-add-box">
            Add a Box to this page
        </a>
    </div>
    <div id="oc-boxes-editor-tools">
        <div class="oc-boxes-editor-tools__inner">
            <div class="oc-boxes-editor-tools__left">
                <div title="Reference" class="oc-boxes-box-reference-indicator">
                    <svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M16.333 7.53a.543.543 0 0 0-.548 0L9.54 11.173l6.52 3.803 6.518-3.803zm6.788 4.583-6.519 3.803v6.52l6.25-3.646a.543.543 0 0 0 .27-.469zm-7.605 10.322v-6.519l-6.52-3.803v6.208a.543.543 0 0 0 .27.47l6.25 3.645z" style="stroke-width:0.724328"/><path d="M8.585 3.134a.543.543 0 0 0-.547 0L1.792 6.777l6.52 3.803 6.518-3.803Zm-.817 14.905V11.52L1.25 7.717v6.208c0 .193.103.372.27.47l6.25 3.645z" style="opacity:0.599407;stroke-width:0.724328"/></svg>
                </div>
                <div class="oc-boxes-editor-tools__label oc-boxes-box-label"></div>
            </div>
    
            <div class="oc-boxes-editor-tools__label oc-boxes-toolbar">
                <a
                    href="#"
                    title="Add Box above"
                    class="oc-boxes-toolbar__action js-boxes-action-add-before"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="oc-boxes-toolbar__icon oc-boxes-toolbar__icon--plus"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        stroke-width="2"
                    >
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4"/>
                    </svg>
                </a>
                <a
                    href="#"
                    title="Duplicate"
                    class="oc-boxes-toolbar__action js-boxes-action-duplicate"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="oc-boxes-toolbar__icon oc-boxes-toolbar__icon--duplicate"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        stroke-width="2"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M8 7v8a2 2 0 002 2h6M8 7V5a2 2 0 012-2h4.586a1 1 0 01.707.293l4.414 4.414a1 1 0 01.293.707V15a2 2 0 01-2 2h-2M8 7H6a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2v-2"
                        />
                    </svg>
                </a>
                <a
                    href="#"
                    title="Delete"
                    class="oc-boxes-toolbar__action js-boxes-action-delete"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="oc-boxes-toolbar__icon oc-boxes-toolbar__icon--trash"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        stroke-width="2"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                        />
                    </svg>
                </a>
                <a
                    href="#"
                    title="Move up"
                    class="oc-boxes-toolbar__action js-boxes-action-move-up"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="oc-boxes-toolbar__icon"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        stroke-width="2"
                    >
                        <path stroke-linecap="round" stroke-linejoin="round" d="M7 11l5-5m0 0l5 5m-5-5v12"/>
                    </svg>
                </a>
                <a
                    href="#"
                    title="Move down"
                    class="oc-boxes-toolbar__action js-boxes-action-move-down"
                >
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="oc-boxes-toolbar__icon"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        stroke-width="2"
                    >
                        <path stroke-linecap="round" stroke-linejoin="round" d="M17 13l-5 5m0 0l-5-5m5 5V6"/>
                    </svg>
                </a>
            </div>
        </div>
    </div>
    <div id="oc-boxes-box-placeholder">
        <div class="oc-boxes-box-placeholder__header">
            <div class="oc-boxes-box-placeholder__label">
                Pending Box
            </div>
    
            <div>
                <svg class="oc-boxes-box-placeholder__icon" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3"/>
                </svg>
            </div>
        </div>
        <div class="oc-boxes-box-placeholder__preview">
    
        </div>
    </div>
    
    <div id="oc-boxes-box-focus"></div>
            </main>
        </div>
    </body>
    </html>

This is the full page Html and not a Json, that's why there is the error saying that the "<" of the opening doctype is not a valid json.

I have nothing in the system.log

Let me know if you need something else.

EDIT : I'm with php 8.3
EDIT2 : If needed, I can send you access to backoffice and ftp in PM, just give me an email to send the infos

**Comment by Zmove** [comment]
I reinstalled a new october install, copied all datas and theme and now, it works....

I can still give you access if you want to understand what happened, probably related to an update. Can't say more about it.

**Comment by tobias-kuendig** [comment]
@Zmove let me know if the problem appears again. I was unable to reproduce it using the version you specified. 

Thank you for the report, anyways!
