### ISSUE TITLE
Boxes relation - fullscreen rich editor insert table bug

### ISSUE THREAD

**Issue by sikhub** [OFFLINE-GmbH/oc-boxes-support#155]
**Describe the bug**
When Boxes are [implemented into custom plugin](https://docs.boxes.offline.ch/use-cases/usage-in-plugins.html#use-the-boxes-editor-in-a-custom-plugin) and fullscreen rich editor is in use we can see a bug when inserting table. In fullscreen we can see that a "insert table popup" is missing.

**Boxes Version**
v3.6.18

**To Reproduce**
1. Implement Boxes into custom plugin
2. Add box with rich editor field
3. Open rich editor in fullscreen
4. Insert table

**Screenshots**
![rich-editor-fullscreen-table-insert](https://github.com/user-attachments/assets/3f140e7b-c5b9-4634-976b-955308558e6a)

**Comment by tobias-kuendig** [comment]
Thank you @sikhub for this report. I can confirm that this is a z-index issue.

**Comment by AgencijaEpic** [comment]
Hi @tobias-kuendig. Is there an intent to fix this z-index issue?

**Comment by tobias-kuendig** [comment]
Yes, sure! I'll try to implement a fix in the next few hours.

**Comment by tobias-kuendig** [comment]
This is fixed in v3.6.30, thank you for the report!

**Comment by sikhub** [comment]
Thanks for quick response!
