### ISSUE TITLE
Child pages do not show up in static page menu

### ISSUE THREAD

**Issue by frthjf** [OFFLINE-GmbH/oc-boxes-support#16]
**Describe the bug**
Using the static page plugin, it appears that the nested menu items are not generated correctly.

**Boxes Version**
v2.0.68

**To Reproduce**

1. Set up a nested set of pages.

![image](https://user-images.githubusercontent.com/5411942/192130570-212f7141-1f64-4301-a46f-842fc9402e78.png)

2. Create a single static menu item to display all pages

![image](https://user-images.githubusercontent.com/5411942/192130594-8df6753c-1f5e-45f3-91fb-2e454753bdd8.png)

Expected: Generates the menu including the nested pages ("Test" > "Nested", "Page")

Observed: Only the top-level menu is generated ("Test")

**Comment by tobias-kuendig** [comment]
Thank you for this report @frthjf!

Can you make sure that your nested pages have an URL? Pages without URLs are ignored in the menu structure.

Also, please make sure to update to the latest version of the plugin as we have added some optimizations to the menu code just recently.

**Comment by frthjf** [comment]
Hi @tobias-kuendig,

Thanks for the quick response.

On v2.0.68, I've got the following error

![image](https://user-images.githubusercontent.com/5411942/192338635-6f35ca4f-0716-4fdf-ae70-29f11388a6f5.png)

but upgrading to v2.0.71 fixed that, so everything is working now. Thanks!

**Comment by tobias-kuendig** [comment]
Great, thank you!
