### ISSUE TITLE
Can't alter component property like octobercms standard

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#164]
**Describe the bug**
You can't define dynamic component properties for components attached to a box

**Boxes Version**
v3.7.3

**Code**
See my box code.

HTM : 

    ==
    <?php
    
    function onStart() {
        $this->contact->setProperty('rules', ['Message' => 'required']);
        dump($this->contact);
    }
    
    ?>
    ==

    <section id="form" class="{% if box.background == 'green' %}c-white bg-jungle-green py-lg{% elseif box.background == 'grey' %}bg-cosmic-latte py-lg{% endif %}">
        <div class="container">
            <div class="grid grid-12 align-start">
                <div class="start-3 span-8">
                    {% if box.title %}
                        <h2 class="mb-md">{{ box.title }}</h2>
                    {% endif %}
                    {{ form_ajax('contact::onFormSubmit', { validate: true, files: true, class: 'form col g-xs' }) }}
                        <div class="grid grid-2 align-start">
                            {% partial '_forms/text' name="Prénom" label="Prénom <span>*</span>" placeholder="Votre prénom" %}
                            {% partial '_forms/text' name="Nom" label="Nom <span>*</span>" placeholder="Votre nom" %}
                        </div>
                        <div class="grid grid-2 align-start">
                            {% partial '_forms/text' name="Email" label="Email <span>*</span>" placeholder="Votre email" %}
                            {% partial '_forms/text' name="Téléphone" label="Téléphone <span>*</span>" placeholder="Votre téléphone" %}
                        </div>
                        {% partial '_forms/text' name="Objet" placeholder="Votre objet" label="Objet <span>*</span>" %}
                        {% if store is empty %}
                            {% set magasins = {} %}
                            {% for store in stores %}
                                {% set magasins = magasins | merge({ (store.slug ~ '') : store.title }) %}
                            {% endfor %}
                            {% partial '_forms/select' name="Magasin" label="Ville / Magasin <span>*</span>" items=magasins %}
                        {% else %}
                            <input type="hidden" name="Magasin" value="{{ store.slug }}">
                        {% endif %}
    
                        {% partial '_forms/radios' name="Expérience" class="field-button" flex="row g-xs" label="Avez-vous déjà de l'expérience dans la vente de parquets et/ou carrelages ? <span>*</span>" default='non' items={'oui': 'Oui', 'non': 'Non'} %}
    
                        {% partial '_forms/textarea' name="Message" placeholder="Votre message" label="Message <span>*</span>" %}
    
                        <div class="mt-md">
                            {# {% partial '_forms/recaptcha' comment="Lorem Ipsum" %} #}
                            <button class="btn btn-lg btn-primary w-100" type="submit" data-attach-loading>{{ "Envoyez un message"|_ }}</button>
                        </div>
                        <div id="{{ contact.alias }}_forms_flash"></div>
                    {{ form_close() }}
                </div> 
            </div>
        </div>
    </section>

YAML : 

    name: Formulaire
    handle: form
    section: Avancé
    
    spacing:
    - general
    
    components:
        contact:
            component: uploadForm
            # addToLayout: true
            properties:
                group: "Formulaire de contact"
                rules:
                    Nom: required
                    Email: required
                messages_success: "Votre formulaire a été envoyé avec succès"
                messages_errors: "Il y a eu des erreurs dans votre formulaire"
                mail_enabled: 1
                mail_subject: "[{{ record.date }}] - {{ form.Nom }} - {{ form.Objet }}"
                mail_recipients: 
                    - mail@test.fr
                mail_replyto: "Email"
                mail_uploads: 1
                reset_form: 1
                feedback_mode: "inline"
                sanitize_data: "disabled"
                anonymize_ip: "disabled"
                recaptcha_enabled: 1
                recaptcha_theme: "light"
                recaptcha_type: "image"
                recaptcha_size: "invisible"
                emails_date_format: "d/m/Y"
                uploader_enable: 1
                uploader_label: "Déposez vos fichiers"
                maxFiles: 5
                maxFileSize: "2MB"
                maxTotalSize: "5MB"
                fileTypes[application/pdf]: "pdf"
                fileTypes[application/zip]: "zip"
                fileTypes[image/png]: "png"
                fileTypes[image/jpeg]: "jpg"
    
    form:
        fields:
            title:
                label: Titre
                type: text
    
        tabs:
            fields:
                background:
                    type: mixin
                    tab: Configuration

When I dump $this->contact in my onStart method, I can see the altered property that validate "Message" instead of "Nom" and "Email", but when I validate the form, it still the "Nom" and "Email" field that are validated, it seems. It like component has already been initialized and can't be modified, didn't find a way to do it.

Thank you

**Comment by tobias-kuendig** [comment]
This is a limitation of October's lifecycle: The Box partial is not re-rendered when you call the `onSubmit` ajax handler, therefore your `onStart` code is never run.

To solve this, you either have to place the logic in your `uploadForm` component. There you can access the Box and all its data.

See https://docs.boxes.offline.ch/use-cases/components.html#accessing-boxes-inside-the-component

```php
<?php
    // in your Component
    public function boxesInit()
    {
        if ($this->methodExists('getBoxesBox')) {
            $boxesBox = $this->getBoxesBox();

            $this->setProperty('rules', $boxesBox->some_custom_logic);
        }
    }
```

If you don't want to move the logic in the component, use one of October's many events to hook into the request cycle and set your properties there.

See https://octobercms.com/docs/api/cms/ajax/beforerunhandler
