### ISSUE TITLE
Enable group mode for repeaters

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#17]
In normal backend forms, it is possible to use group mode in repeaters to allow the selection of different types of forms to be used in a repeater.  

EG.
content:
    type: repeater
    prompt: Add content block
    groups: $/acme/blog/config/repeater_fields.yaml

https://docs.octobercms.com/2.x/backend/forms.html#repeater

This is very handy for allowing flexible outputs through one repeater instead of using trigger events to hide/display form fields. 

It would be great if the boxes plugin allowed this mode to be used.

**Comment by tobias-kuendig** [comment]
The boxes plugin renders a standard Backend form, so we should not have to add anything special.

I have also used the group mode successfully in Boxes before. 

Do you get an error? Can you share some code?

**Comment by roojai** [comment]
That sounds good, but yes I have been getting errors, so I thought it was not supported yet.

I get an error: 

Undefined array key "form"

The code I am using is this: 



              buttons:
                  label: Buttons
                  prompt: 'Add new button'
                  maxItems: '3'
                  span: full
                  type: repeater
                  tab: Section
                  groups: $/roojai/forms/config/buttonfields.yaml



This works ok in normal backend forms for me, but just not in the boxes plugin


![image](https://user-images.githubusercontent.com/31172173/192721809-198ba41a-15a5-4870-888a-4c9545ae3075.png)

**Comment by tobias-kuendig** [comment]
You can work around this by adding an empty fields section:

```
form:
    fields:
```

I'll see that I can release a bugfix soon.

**Comment by roojai** [comment]
Ah, thats great to know! Thanks

**Comment by tobias-kuendig** [comment]
This is fixed in v2.0.73, thanks again for the report, @roojai! :+1:
