### ISSUE TITLE
Can't uninstall in SQLite environment

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#173]
**Describe the bug**
I tried to uninstall / reinstall boxes to see if a fresh reinstall can fix [this issue](https://github.com/OFFLINE-GmbH/oc-boxes-support/issues/167).

When I try to uninstall, I get the following error : 

    SQLite doesn't support multiple calls to dropColumn / renameColumn in a single modification.

As the error say, I'm in SQLite environment

![image](https://github.com/user-attachments/assets/f36aeae0-b6ae-4a3d-9fab-693279482719)

Thank you

**Comment by tobias-kuendig** [comment]
Thank you @PubliAlex, this now works in v3.6.43.
