### ISSUE TITLE
Can't add a custom relation to a box

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#18]
**Describe the bug**
Extend a box to add a custom relation don't work.

**Boxes Version**
v2.0.72

**To Reproduce**
1. Create plugin with a model
2. Try to add a relation to that model a box by following [this documentation](https://docs.boxes.offline.ch/use-cases/relations.html#additional-relations)
3. Add the box containing that relation in a page
4. You should get "`Could not translate relation type 'attachMany' to a valid field type" on line 149 of /modules/backend/formwidgets/Relation.php`" error

**Code**

    public function boot()
    {
        parent::boot();
    
        \OFFLINE\Boxes\Models\Box::extend(function (Box $box) {
            $box->attachMany['categories'] = \XXX\Researches\Models\Category::class;
        });
    }

**Comment by PubliAlex** [comment]
Resolved by using belongsToMany instead of attachMany

**Comment by tobias-kuendig** [comment]
Thank you @PubliAlex. The example in the docs was actually misleading and wrong. I have replaced it with a better example.
