### ISSUE TITLE
Copying over other site language not working

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#181]
I have this pages

![image](https://github.com/user-attachments/assets/72fff211-168b-4d66-9616-20a60935c4f4)

and nothing happens when I try to copy them over the second site language

![image](https://github.com/user-attachments/assets/85a75f44-5a96-4016-acf2-37797104337b)

**Comment by tobias-kuendig** [comment]
When copying a page, the subpages are currently not copied as well. You'd have to copy all sites one-by-one.

**Comment by chrisvidal** [comment]
yes this is what I am doing, but they do not get copied over

**Comment by chrisvidal** [comment]
https://github.com/user-attachments/assets/91452636-d461-4e14-a67a-40fa4eb703a4

**Comment by tobias-kuendig** [comment]
Your EN home page has the "Frontend" page set as its main page, this could make problems when you copy the page to the other site, because it cannot match the two.

**Comment by chrisvidal** [comment]
Im not sure to understand this "page on main site" dropdown functionality ?

**Comment by tobias-kuendig** [comment]
It sets the `site_root_id` of the page. This is just October's multi-site implementation that allows you to link different models on different Sites together. 

You can have a page on each of your Sites, but one is usually the primary ("This page is main"). All the other pages on the other sites link to that primary page. So when you switch between sites, October automatically knows to what page you need to be redirected.

**Comment by chrisvidal** [comment]
I see.
so, on my EN website, all the pages would be "this page is main"
on my Thai website, all the pages would be what then ?

**Comment by tobias-kuendig** [comment]
Right, you usually don't have to set this value yourself, Boxes should handle it automatically.

**Comment by chrisvidal** [comment]
Since i could change it, I was confused and thought I had to choose myself hehe.
thanks, let me try now to copy over with that understanding
