### ISSUE TITLE
Cannot update CMS to October 3.1 without fatal error from the Boxes plugin

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#21]
**Describe the bug**
Cannot update CMS to October 3.1 without fatal error from the Boxes plugin :
Call to a member function getPath() on null
~/plugins/offline/boxes/classes/partial/PartialReader.php line 44

It seems impossible to reverse the issue and both the backend and frontend are displaying the error. 

**Boxes Version**
v2.0.80
v2.0.82

**To Reproduce**
I tried updating October using "php artisan october:update" while running Boxes v.2.0.80 and the error occurred.

If I remove the boxes plugin from the system, then I can successfully update OCMS to 3.1

If I tried updating the Boxes plugin first to v2.0.82 and then updating OCMS, and the same issue occurs.

**Comment by tobias-kuendig** [comment]
@roojai there was a breaking change introduced in October 3.1. Please upgrade Boxes first to version `2.0.82`, then update to October 3.1.

**Comment by roojai** [comment]
yes I did try that, as I said above. But still have the same issue. I will try again

**Comment by tobias-kuendig** [comment]
@roojai  Thank you for this report. It seems like October does no longer resolve the active Theme correctly during migrations in some circumstances. 

I have just released v2.0.83 with a possible fix. Does the update work for you?

**Comment by roojai** [comment]
Thanks @tobias-kuendig 

I get a different error now.

The "/partials/" directory does not exist.
~/vendor/symfony/finder/Finder.php line 590

Perhaps I need to update the default theme in 

config/cms.php

'active_theme' => env('ACTIVE_THEME', 'demo'),

**Comment by tobias-kuendig** [comment]
Do you have a default theme set? I cannot reproduce the issue on my end, but the errors means that no "active theme" is set.

**Comment by tobias-kuendig** [comment]
I have released another update you can try

**Comment by roojai** [comment]
Thanks for your quick work!
Now the update does succeed without error but then I have issues with "The active theme is not found." I can access the backend without errors, but the frontend theme does not work/is not recognised.

I thought perhaps an issue with OctoberCMS, so I tested again, and if I remove the Boxes plugin before the update, then I do not get this issue.

**Comment by tobias-kuendig** [comment]
> "The active theme is not found."

Do you have a stack trace for this error, so we can see where it originates from?

**Comment by roojai** [comment]
In the backend I have:

![image](https://user-images.githubusercontent.com/31172173/194515524-eb36aedb-55a1-4fd6-bc35-ded95d61960d.png)

The theme 'roojai-tailwind' is not found. - but this is my theme name in slug form.

Its a bit strange as my theme.yaml is like this: 

name: 'Roojai Tailwind'
description: 'Roojai Theme'
author: Roojai
homepage: www.roojai.hk
authorCode: Roojai
code: RoojaiTailwind
parent: ''
database: '0'
form: config/fields.yaml
previewimage: assets/theme/roojai-01.png

in .env I am setting: ACTIVE_THEME=RoojaiTailwind
(using the theme code)

Frontend:

The active theme is not found.
~/modules/cms/classes/Controller.php line 120


public function __construct($theme = null)
    {
        $this->theme = $theme ?: Theme::getActiveTheme();
        if (!$this->theme) {
            throw new CmsException(Lang::get('cms::lang.theme.active.not_found'));
        }
  
<html>
<body>


# | CALLED CODE | DOCUMENT | LINE
-- | -- | -- | --
41 | Cms\Classes\Controller->__construct() |   |  
40 | ReflectionClass->newInstanceArgs() | ~/vendor/laravel/framework/src/Illuminate/Container/Container.php | 915
39 | Illuminate\Container\Container->build() | ~/vendor/laravel/framework/src/Illuminate/Container/Container.php | 756
38 | Illuminate\Container\Container->resolve() | ~/vendor/laravel/framework/src/Illuminate/Foundation/Application.php | 860
37 | Illuminate\Foundation\Application->resolve() | ~/vendor/laravel/framework/src/Illuminate/Container/Container.php | 692
36 | Illuminate\Container\Container->make() | ~/vendor/laravel/framework/src/Illuminate/Foundation/Application.php | 845
35 | Illuminate\Foundation\Application->make() | ~/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php | 338
34 | Illuminate\Support\Facades\Facade::__callStatic() | ~/modules/cms/classes/CmsController.php | 64
33 | Cms\Classes\CmsController->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
32 | Illuminate\Routing\Controller->callAction() | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php


</body>
</html>

**Comment by tobias-kuendig** [comment]
Does it work if you set `ACTIVE_THEME` to the name of the theme folder?

**Comment by roojai** [comment]
Yes that works!! Thanks a lot! I really appreciate the support especially as the issue seemed related to my own specific theme set up (or lack of it)

Sorry to have cost the time, and glad we got there

**Comment by tobias-kuendig** [comment]
No worries, glad we figured that one out!
