### ISSUE TITLE
Fatal error with latest 2.x version of translate plugin

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#23]
**Describe the bug**
Translate plugin just been updaded to works with octobercms 3.1.x, it seems Boxes need an update too to support it

**Boxes Version**
v2.0.85

**To Reproduce**
Update octobercms 3 to make sure you also have translate plugin to version 2.x

**Screenshots**
![image](https://user-images.githubusercontent.com/55833027/195032792-c23207c7-e98f-4781-88ac-335eeda72dd5.png)

**Comment by tobias-kuendig** [comment]
Thank you for the report, @PubliAlex! 

Version v2.0.86 has just been released that improves interoperability witih version 2.0 of RainLab.Translate. Proper multi-site support in Boxes is right around the corner.
