### ISSUE TITLE
Error when using boxes as a form widget in tailor entry

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#24]
**Describe the bug**
When saving a tailor entry containing boxes content, you get an error 

`"Class "Tailor\Models\EntryRecord@xc_be61055ccd4b4b4ab1c6b9c4129f5ba5c" not found"`

**Boxes Version**
v2.0.89

**To Reproduce**
1. Create a tailor entry
2. Put boxes content in it like this : 
3. Create a new entry
4. Save it, see the error

**Code**
Here is a code example of my tailor entry

    uuid: be61055c-cd4b-4b4a-b1c6-b9c4129f5ba5
    handle: Blog\Post
    type: stream
    name: Articles de blog
    drafts: true
    
    primaryNavigation:
        label: Blog
        icon: icon-bookmark
        order: 15000
    
    navigation:
        icon: icon-bookmark
        parent: MyStream
        order: 10
    
    fields:
        boxes_content:
            span: adaptive
            type: boxes
            previewLayout: blog

**Screenshots**
![image](https://user-images.githubusercontent.com/55833027/195566972-28ad481c-ea66-4934-92d3-5954414eca22.png)

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you for the report! This is fixed in v2.0.90
