### ISSUE TITLE
Editor October CMS. .yaml files

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#26]
# 💡 Do not post your feature request as an issue!

Editor October CMS is not supported in the editor .yaml files. I propose to work out this solution

![image](https://user-images.githubusercontent.com/40325840/196028837-a2aa80ee-6502-49a3-a258-fc45227fee88.png)

**Comment by patrick-durrer** [comment]
Thanks for your Feedback.

As you mentioned, this is less a missing feature from the Boxes plugin and more a limitation of the October CMS editor.

As soon as the October CMS supports the editing of YAML files in de partials folder, nothing should prevent editing the boxes YAML-Files in the backend editor.

**Comment by tobias-kuendig** [comment]
This feature is also track in #4 

The Editor has a complete Extension system that would allow us to edit Boxes partials in the backend. Unfortunately, the extension system is currently largely undocumented so the implementation is very cumbersome.
