### ISSUE TITLE
Editor CSS styles conflict

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#27]
editor styles influence design styles

![image](https://user-images.githubusercontent.com/40325840/196252260-e59dfe8b-9724-4e90-9c5d-69f9030cbb59.png)

**Comment by patrick-durrer** [comment]
Thank you for this report! This is actually a known issue that we try to resolve. There was already a small fix in version 2.0.87 and 2.0.88.
 
We are trying to optimize this even further.

**Comment by sellscompany** [comment]
Good! Thanks!

**Comment by tobias-kuendig** [comment]
This is fixed in v2.0.93, thank you for the report!
