### ISSUE TITLE
Position in the menu

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#28]
# 💡 Do not post your feature request as an issue!
I suggest making an option for the location of the plugin in the menu first. Useful for small sites when you need to quickly go in and edit content

![image](https://user-images.githubusercontent.com/40325840/197344653-f4548fe5-55a6-4e7b-a645-4ec6263ecee8.png)

**Comment by tobias-kuendig** [comment]
Great suggestion! v2.1.8 supports overriding this option using `BOXES_MAIN_MENU_ORDER=1`  in your .env file.
