### ISSUE TITLE
Remove the Boxes code from the published version

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#29]
There are cases when such a solution interferes

![image](https://user-images.githubusercontent.com/40325840/197344726-74a456b1-8cd8-4442-8f20-f33fbeb17687.png)

**Comment by tobias-kuendig** [comment]
Thank you for this input! Starting from version `v2.1.7` you can now configure Boxes to not include this markup in the generated output.

See https://docs.boxes.offline.ch/getting-started/configuration.html
