### ISSUE TITLE
Draft and published

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#30]
Offer to make 2 page status (draft and published)

![image](https://user-images.githubusercontent.com/40325840/197345016-020f9cab-6298-4f28-a216-13201b834e7b.png)

**Comment by patrick-durrer** [comment]
For now, we're using the "Hidden" flag to create draft pages that are only visible to logged-in users. On the other hand, the site-specific settings can be easily expanded (https://docs.boxes.offline.ch/use-cases/page-specific-data.html#custom-attributes):

e.g.:
```
Event::listen('backend.form.extendFields', function ($widget) {
  $widget->addFields([
      'custom_config[state]' => [
          'label' => 'Status',
          'type' => 'dropwdown',
          'options' => ...
          [...]
});

**Comment by tobias-kuendig** [comment]
Thank you for this input, we already track this issue in #2
