### ISSUE TITLE
Trigger doesn't work in .yaml

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#31]
![image](https://user-images.githubusercontent.com/40325840/197345182-0c2e858f-0801-44a7-a1b5-b4d8cac3900b.png)

**Comment by patrick-durrer** [comment]
I see two possible issues in your code:

1. The `trigger` itself does not react to changes from another field. To do this, a `dependsOn` must be defined. 
2. The conditional value must also be specified as `condition: value[]`. 

Here's an example that I think should work:

```
form:
    tabs:
        fields:
            view:
                type: dropdown
                options:
                    1: Option 1
                    2: Option 2
            slider:
                type: repeater
                trigger:
                    action: show
                    field: view
                    condition: value[2]
                dependsOn: view

**Comment by sellscompany** [comment]
Yes, I was wrong. Thanks!
