### ISSUE TITLE
Strange page reload in the backend when clicking a tab

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#34]
**Describe the bug**

When editing a page in the backend, if I click on a section for editing, and then if I click a tab in the now active box section, the page suddenly reloads and I need to click into the section again.  

**Boxes Version**
This just started after version 2.0.90 or 2.0.91. I tested and 2.0.89 does not have this bug.

**To Reproduce**
1. Open 'Content' in the backend and then click on a page to edit
2. Click on a section to edit and this will bring up the Box submenu/editing interface
3. Click on a tab to access other fields
4. Page reloads and you need to click on the section again.

![image](https://user-images.githubusercontent.com/31172173/199891505-adcbc78b-b268-4e2a-adc0-296e42f2fa8c.png)

**Comment by tobias-kuendig** [comment]
Thank you for the report @roojai! The change that introduced this bug has been reverted in v2.0.92.
