### ISSUE TITLE
Issue with boxes with components included in tailor

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#36]
**Describe the bug**

I have a box including a component (magic form), that works well when I create a box page.

If I add that same box in a tailor model and try to submit my form, it says : 

![image](https://user-images.githubusercontent.com/55833027/200788144-1a64dbc4-0472-498c-8f0f-836e2e797b2b.png)

**Boxes Version**
v2.0.92

**To Reproduce**

1. Create a box with a component using an ajax call
2. Create a tailor model, add boxes field to that model
3. Add the box including an ajax component to your tailor model
4. Save your model
5. Go to see it in the frontend
6. Try to use your component, you will het the not found method error

**Additional context**
This is a typical bug when an ajax component is included in a partial and not in a page, the method cannot be found. It seems that box plugin is unable to "move" the component to the page when it's included in tailor content (whereas it works well when added to page).

The strange thing is that it works when I'm on the model editing page in backoffice, but not when I see the result in frontoffice.

**Comment by tobias-kuendig** [comment]
Thank you for this report, @PubliAlex!

There's no easy method to initialize the components on the partials automatically when using these partials in Tailor. The only efficient method is to initialize the partials manually, so we opted for that solution.

It just requires you to add a call to an `->init()` method whenever your page is initialized. This will register all components so the AJAX handlers work correctly.

This topic is documented here:  https://docs.boxes.offline.ch/use-cases/usage-in-plugins.html#manually-initializing-partials

Let me know if you have any further questions!

**Edit**: This change only works with v2.1.6+
