### ISSUE TITLE
Localization: Editing box content in one language affects the other language

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#37]
**Describe the bug**
Editing box content in one language affects the other language

**Boxes Version**
v2.0.93

**To Reproduce**
1. Include rainlab/translate-plugin
2. Set fields as translatable as instructed here: https://docs.boxes.offline.ch/use-cases/localization.html
3. Click on 'content' to edit content. You will see that the field now shows the language/site icon
4. If you select primary site and edit the field and save, then change to another language it will show the same data as last saved (no matter what language is selected).

Perhaps I am doing this wrong, but my other plugins that use rainlab/translate-plugin are working ok. I am just unsure how to view/save the difference language version with the boxes editor.

Video of the issue: https://youtu.be/Bcfi4ytsNRk

**Comment by tobias-kuendig** [comment]
Thank you for this report @roojai.

Support for October's multi-site feature is not yet available for the Boxes plugin (but is being actively developed). Currently, only rainlab-translate v1 is supported for mutli language sites.

I'll update this issue as soon as the multi-site support is available.

**Comment by roojai** [comment]
ok, thanks.

**Comment by tobias-kuendig** [comment]
Version `v2.1.1` has just been released with initial support for the multisite feature.

Let me know if you notice any issues.

https://docs.boxes.offline.ch/use-cases/multisite.html

**Comment by roojai** [comment]
Thanks @tobias-kuendig! 

I will give it a go. FYI, for some reason, if I try to update the plugin from the backend plugins area it fails (and I lose all data too). Works fine with the console update though. I find that happens sometimes with Octobercms V3....

**Comment by tobias-kuendig** [comment]
Do you lose all data in the database or only the UI? The upgrade routine clears the cache, and this is important. After the update the pages are stored a bit differently, so no old cache data must be around.

In no case should the migration wipe your database tables, though.

**Comment by roojai** [comment]
The tables were still there. 
But there is an error in the updating:

"Update Failed
Attempt to read property "slug" on null"

And the plugin stays at 2.1.0

At this point the pages built with Boxes appear to be wiped, but they are still in the database, just not accessible through the UI nor through the URL's (frontend).

Anyway, the update works fine with the composer method from a console.

**Comment by roojai** [comment]
@tobias-kuendig there now appears to be an issue when using boxes within a custom plugin. 

I get this message when I try to save my model:
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'offline_boxes_pages.content_type' in 'where clause' (SQL: select * from `offline_boxes_pages` where (`offline_boxes_pages`.`content_type` = Roojai\Business\Models\Service and `offline_boxes_pages`.`content_id` = 3 and `offline_boxes_pages`.`content_id` is not null or offline_boxes_pages.id in (select `slave_id` from `deferred_bindings` where `master_field` = layoutboxes and `master_type` = Roojai\Business\Models\Service and `session_key` = QLampJnrELQxsoThlNwPbhd0hRW5gkE8hSYVikaT and `is_bind` = 1)) and offline_boxes_pages.id not in (select `slave_id` from `deferred_bindings` where `master_field` = layoutboxes and `master_type` = Roojai\Business\Models\Service and `session_key` = QLampJnrELQxsoThlNwPbhd0hRW5gkE8hSYVikaT and `is_bind` = 0 and id > ifnull((select max(id) from deferred_bindings where slave_id = offline_boxes_pages.id and master_field = layoutboxes and master_type = Roojai\Business\Models\Service and session_key = QLampJnrELQxsoThlNwPbhd0hRW5gkE8hSYVikaT and is_bind = 1 ), 0)) and `offline_boxes_pages`.`site_id` = 1 and (`theme` = roojai-tailwind or `theme` is null) order by `created_at` desc, `nest_left` asc limit 1)" on line 760 of ....

**Comment by roojai** [comment]
Oh, I found that I can fix it by  changing this:


public $morphOne = [
        'your_relation' => [    // Any name you want
            \OFFLINE\Boxes\Models\Page::class,
            'name' => 'content' // Has to be called 'content'
        ]
    ];
to this:

public $morphOne = [
        'your_relation' => [    // Any name you want
            \OFFLINE\Boxes\Models\Content::class,
            'name' => 'content' // Has to be called 'content'
        ]
    ];

**Comment by tobias-kuendig** [comment]
Ah yes, I'm sorry, this is an undocumented change. I'll add a note to the docs for that.

**Comment by tobias-kuendig** [comment]
The information has been added here: https://docs.boxes.offline.ch/getting-started/migration-guide.html

**Comment by roojai** [comment]
Hi @tobias-kuendig 

It would be wonderful if the support for the multi-site feature could also work for use in custom plugins. Currently the same issue that used to exist with pages, exists with my own custom models

**Comment by tobias-kuendig** [comment]
Can you share some details about your implementation? When using Boxes as an Editor in a custom plugin, you'll have to implement the Multisite trait on your model yourself. This will create a new copy of your model for each site, where the Boxes Content model will be attached to. 

This means the Multisite implementation happens outside of Boxes in these cases.

**Comment by roojai** [comment]
Hi @tobias-kuendig 

Thanks for following up. Yes, my implementation is wrong. I was using the translate plugin and that works fine for most fields so I thought it might be ok to use it for boxes too. 

I was unaware of the Multisite trait, the Octobercms documentation for it is quite hidden!!

I have now read the docs and implemented in my model: 

    use \October\Rain\Database\Traits\Multisite;
    protected $propagatable = [];

It seems to work ok. However when I switch sites and the system create a new model for the 2nd site, I get this warning:

"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AzPwmmsPyvhD' for key 'offline_boxes_content_slug_unique' (SQL: insert into `offline_boxes_content` (`slug`, `layout`, `theme`, `content_id`, `content_type`, `is_pending_content`, `custom_config`, `updated_at`, `created_at`) values (AzPwmmsPyvhD, default, roojai-tailwind, 16, Roojai\Services\Models\Treatment, 0, ?, 2022-11-29 09:45:02, 2022-11-29 09:45:02))" on line 760 of /home/779131.cloudwaysapps.com/yncbvghyrk/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php


But I can ignore this warning and access the new model on the second site and add the alternative content.  So it works!

**Comment by tobias-kuendig** [comment]
Great! This issue was fixed in v2.1.9 while testing your bug report a few hours ago. After an update you should not see the error again!
