### ISSUE TITLE
Rich editor shows no formatting when using boxes editor

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#38]
**Describe the bug**
If you set up a rich editor field in the yaml file for a partial, and then view the editor using the boxes editor, then formatting such as paragraph spacing, list bullets, headings etc do not show (but they are added and saved)

**Boxes Version**
has been present in all versions up to v2.1.1

**To Reproduce**
Steps to reproduce the behaviour:
1. add rich editor field in the yaml file
2. view the richeditor field using the boxes editor
3. Try to add bullets or text with formatted headings/paragraph tags
4. Will see no formatting in editor

**Comment by tobias-kuendig** [comment]
This is fixed in v2.1.3, thank you for the report!
