### ISSUE TITLE
Editor Page not loaded when using boxes as a form field

### ISSUE THREAD

**Issue by EricNiedergang** [OFFLINE-GmbH/oc-boxes-support#39]
**Describe the bug**
It's quite hard to explain, so lets give an example with images : 

I'm using boxes to edit blog content, the blog is made using tailor. Here is my blog post definition : 

    uuid: be61055c-cd4b-4b4a-b1c6-b9c4129f5ba5
    handle: Blog\Post
    type: stream
    name: Articles de blog
    drafts: false
    multisite: true
    
    primaryNavigation:
        label: Blog
        icon: icon-bookmark
        order: 15000
    
    fields:
        teaser:
            label: Résumé
            type: textarea
            size: small
            tab: Informations
        image:
            label: Image
            type: fileupload
            maxFiles: 1
            tab: Informations
        boxes_content:
            span: adaptive
            type: boxes
            previewLayout: blog
            tab: Contenu

Here is how my blog articles are rendered. Works as expected for the frontend : 

![image](https://user-images.githubusercontent.com/55832474/203017533-8cda6ebd-1a82-424b-b70f-a43c7a78dbf2.png)

Here is the code for my page, nothing complexe here : 

    url = "/blog/:slug"
    layout = "blog"
    title = "Détail d'un article"
    
    [section post]
    handle = "Blog\Post"
    entrySlug = "{{ :slug }}"
    entryDefault = 0
    fullSlug = 0
    ==
    <section>
        <div id="heading" class="text-center">
            <div class="container-lg">
                <div class="date">{{ post.date|date('d F Y') }}</div>
                <h1 class="h1">{{ post.title }}</h1>
                <div class="text-center">
                    <a class="btn back btn-primary btn-sm" href="{{ 'blog/listing'|page }}">{{ 'Retour'|_ }}</a>
                </div>
                <img class="lazyload img" data-sizes="auto" data-src="{{ post.image|resize(1400,800,{mode:'crop'}) }}" alt="{{ post.image.title }}" />
            </div>
        </div>
        <div id="content">
            {{ post.boxes_content.render() | raw }}
        </div>
    </section>

The issue come from the fact that boxes, when used as a field, ignore the page markup where the model is rendered (so it also ignore the component that load the correct model depending on the :slug paramerer in the URL.

When boxes is used as a field, the preview area should render the whole page containing the article, including all fields that are designed outside the boxes system.

![image](https://user-images.githubusercontent.com/55832474/203018465-13a410f3-2c93-441c-aa79-462afe1ecf81.png)

Whereas it should render this : 

![should](https://user-images.githubusercontent.com/55832474/203020757-49197801-89dd-447d-9e5a-2d4d2e8548be.gif)

**Boxes Version**
v2.1.4

**Comment by tobias-kuendig** [comment]
Thank you for the feedback!

Boxes does currently not support using a specific page for the preview, only a specific layout. I'll leave this issue open to track progress. I'll see how we can implement this.

**Comment by tobias-kuendig** [comment]
As a workaround for the time being, you could put the blog header in a separate layout and use the `previewLayout` option to use that layout instead.

https://docs.boxes.offline.ch/use-cases/usage-in-plugins.html#use-the-boxes-editor-in-tailor

**Comment by EricNiedergang** [comment]
@tobias-kuendig I tested it, the problem is that the tailor component need the :slug url parameter to get the model. If you put the component to the layout, you don't have access to the url parameter.

**Comment by tobias-kuendig** [comment]
@EricNiedergang I just wanted to let you know that we have this issue on the radar but it is turning out to be more complex than initially thought. 

We probably will introduce a `previewPage` option to cover this use-case.

I'll keep you posted.

**Comment by PubliAlex** [comment]
@tobias-kuendig previewPage option would be perfect.

**Comment by tobias-kuendig** [comment]
Starting from Boxes `v2.1.21` you can now use "Page Templates" to accomplish this: https://docs.boxes.offline.ch/use-cases/page-templates.html

Define a page template for your blog post:

```yaml
# /themes/your-theme/boxes.yaml
templates:
-   name: Blog
    handle: blog
    contexts:
    - blog
    boxes:
    - partial: blog-header # put your blog header in here
      locked: true         # make sure the user cannot edit this Box
```

Then in your `fields.yaml`, make sure to set the `template` option:

```yaml
    fields:
        content:
            label: Content
            span: adaptive
            type: boxes
            template: blog
```

If the user creates a new Blog entry, the `blog-header` Box will automatically be added to newly created page. 

Please keep in mind, that this only works for newly created records.

The `previewPage` option would have been to cumbersome too implement and use. We think this is a better solution to this problem.

Let me know if you have any further questions.

**Comment by PubliAlex** [comment]
@tobias-kuendig you are the boss 👍 , I will try that asap.
