### ISSUE TITLE
I suggest removing the limit of max width and max the height of the icon

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#40]
I suggest removing the limit of max width and max the height of the icon when the column is one, to give customers to see the blocks completely

![image](https://user-images.githubusercontent.com/40325840/205280778-25497937-fa05-4799-886a-8b132b50ff3c.png)

![image](https://user-images.githubusercontent.com/40325840/205281195-07fb004b-66ce-48b6-93e7-8241fbc8331b.png)

**Comment by tobias-kuendig** [comment]
@sellscompany, thank you for this feedback! We have added an issue for this suggestion to our internal roadmap. I will let you know as soon as the feature is available.

In the meantime, the modal has a `oc-boxes-partial-selection-modal` class you can target with custom CSS to change the CSS of the items.
