### ISSUE TITLE
Seo storm integration

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#43]
Hello,

SEO Storm is the way to go when you want to do some SEO with october cms.

Boxes alreay have some SEO fields and it do the job to generate metas, but it would be great if boxes could integrate with SEO storm to be included in the generated sitemap.xml file

Do you think it's possible ?

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you for this suggestion! I do not know the SEO Storm plugin, but I'll take a look at it and will check what an integration would require.

I'll keep you posted.

**Comment by tobias-kuendig** [comment]
@PubliAlex, unfortunately, the SEO Storm plugin does not provide easy methods to inject custom SEO information. It would require some work that we need to get merged in the SEO Storm plugin first. We currently do not have the resources to do this.
