### ISSUE TITLE
Can't click on subpage

### ISSUE THREAD

**Issue by CarolinePublipresse** [OFFLINE-GmbH/oc-boxes-support#45]
**Describe the bug**
I can't click on subpages I just created.

**Boxes Version**
v2.1.29

**To Reproduce**
1. Create 2 pages
2. Use the +  on hover to create a subpage on the second one
3. Save and go back to the first page.
4. try to open the tree to click on the subpage created before.

**Screenshots**
https://www.loom.com/share/446cf7afdd23416da5b625f2d367ad95

**Additional context**
Just bougth and installed the module. I wanted to create my menu tree berore starting to create boxes. Donc't know what I made wrong...

**Comment by tobias-kuendig** [comment]
Thank you for this report!

It looks like the click is triggering a full page reload. Could you check your JS console if you see any errors in there? I'll try to reproduce the issue on my end.

**Comment by CarolinePublipresse** [comment]
I did saw some errors in the console, due to some plugins not setteled yet on the front. But I solved it all, now my console is clean, and I'm still getting the problem.

**Comment by CarolinePublipresse** [comment]
I usually start by the menu and footer integration, so I made a fresh install and did not created block partials yet. When I click on a page, it displays an overlay box whith the error "HTML Element not found". 
Could it be related ?

**Comment by CarolinePublipresse** [comment]
> I usually start by the menu and footer integration, so I made a fresh install and did not created block partials yet. When I click on a page, it displays an overlay box whith the error "HTML Element not found". Could it be related ?

It is not. It was my popup plugin on front page. No relation. I removed it and still have no errors on the console. And I still can't select a subpage. 

Althought, I created a box partial based on the documentation, and it's not showing up for use in the backend

**Comment by CarolinePublipresse** [comment]
PS : I'm on October v3.2.12, and use an sqlLite database

**Comment by CarolinePublipresse** [comment]
Just tried a fresh install with mysql database. Same result.

**Comment by CarolinePublipresse** [comment]
Tried with october Demo theme, and have disabled all other plugins to prevent incompatibilities... Still not ok
![image](https://user-images.githubusercontent.com/84564072/217029703-aa31fe6a-dc7d-40a4-863b-85033221471e.png)
I don't know what is missing...

**Comment by tobias-kuendig** [comment]
Thank you for all the information! Could you run one last test: Does the problem exist in a incognito window or another browser?

**Comment by CarolinePublipresse** [comment]
Same problem on a private session on Chrome, and also on Edge.

**Comment by CarolinePublipresse** [comment]
Nothing on the events log either

**Comment by PubliAlex** [comment]
@tobias-kuendig @CarolinePublipresse I found the solution for the No-block problem, it come from the fact that you have to define your theme in .env file. Define it only in backend multisite page is not enought.

For the subpage issue, I can also confirm the problem in the latest version of boxes. I created a video to show the problem :

https://www.loom.com/share/c728dfbc1dba4d45929abda01a9b9c18

**Comment by PubliAlex** [comment]
@tobias-kuendig I also found a fix for the subpage issue

![image](https://user-images.githubusercontent.com/55833027/217825229-3dec1df4-6cb2-44a7-a1bd-7fa42c30a374.png)

Instead of putting href="#" in your link, you can put javascript:void(0) and it works.

**Comment by tobias-kuendig** [comment]
Thank you @PubliAlex! Could you check if the issue still exists in v2.1.32?

**Comment by CarolinePublipresse** [comment]
I did applied the patch, and it worked. I have then updated the module to v2.1.32 and it seems to work fine :) 
Thanks to you both

**Comment by tobias-kuendig** [comment]
Thank you for the report and testing the fix!

**Comment by CarolinePublipresse** [comment]
> @tobias-kuendig @CarolinePublipresse I found the solution for the No-block problem, it come from the fact that you have to define your theme in .env file. Define it only in backend multisite page is not enought.

I had to move my website from SQLite to MySQL. When triying to add blocks on a page, they were well shown in the list, but on adding one, it showed the following error : 
`"Could not find partial with handle "fb"." on line 146 of [...]/plugins/offline/boxes/classes/partial/PartialReader.php`

It was solved by defining the ACTIVE_THEME variable in the .env file either.
