### ISSUE TITLE
Multilingual variables and models not translated in preview mode

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#46]
**Describe the bug**
When I browe the english version of the website, everything is correctly translated, but in boxes preview mode, translatable models and variables stay in default language.

**Boxes Version**
v2.1.29

**To Reproduce**
1. Install Rainlab.translate
2. Create a translatable variable, for example : {{ 'About us'|_ }}
3. Translate it in the backend
4. Go to your frontend, switch language, it works
5. Go to boxes backend, switch language, it does not work
6. Can also be reproduced with models that implement 

**Screenshots**
In website in english (default language is french)
![image](https://user-images.githubusercontent.com/55833027/217541529-01d67f5b-26a4-4a49-aafd-69d989b533e5.png)

Preview mode in english
![image](https://user-images.githubusercontent.com/55833027/217541787-13fbb5a1-99b5-4f57-87e9-ce1a31e3ab55.png)

**Additional context**
Content is translated using rainlab translate because the website was build before the multisite feature.

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you for this bug report! A fix has been implemented in version 2.1.31.

Let me know if the issue persists.
