### ISSUE TITLE
Bloxk folder position with another theme

### ISSUE THREAD

**Issue by resimone** [OFFLINE-GmbH/oc-boxes-support#47]
**Describe the bug**
Plugin shows me only boxes I've put in /themes/**demo**/partials/blocks folder even if I have another active theme.
To see them working in frontend I have to copy them even in /themes/**offline-mall-theme**/partials/blocks
**offline-mall-theme** is the active theme now...

**Boxes Version**
2.1.30

**Comment by tobias-kuendig** [comment]
Thank you for this report!

Did you reload the backend page when you have changed the theme? The Editor in the backend loads the available partials only when the page is initially loaded.

It is by design that only partials from the active theme are displayed.

Please provide further details (what do you mean "to see them working in frontend"?) if the problem persists.

**Comment by resimone** [comment]
Pretty sure I've reloaded the backend :) 
"select a box" popup seems to be "locked" to the "demo" default theme folder, even if it's not active.
Can't understand why but I've to copy .htm and .yaml files in both paths...

Can I find "type" list, definitions and usage somewhere? 
Can't see a full list in your docs.

**Comment by tobias-kuendig** [comment]
> Can I find "type" list, definitions and usage somewhere?

What do you mean by `type`?

>  Can't understand why but I've to copy .htm and .yaml files in both paths...

Does it work if you run `php artisan cache:clear` on the command line?

In the `PartialReader` class, the `partialsPaths` variable is popuplated right in the constructor. Could you check what path is in use there?

**Comment by Alldar** [comment]
@resimone Make sure that the ACTIVE_THEME parameter in the .env file is the name of your template and not "demo".

**Comment by resimone** [comment]
> @resimone Make sure that the ACTIVE_THEME parameter in the .env file is the name of your template and not "demo".

You're right Alldar, that fixed the problem, thanks!!

**Comment by tobias-kuendig** [comment]
Great to hear, thank you @Alldar!
