### ISSUE TITLE
Error on tables migration after installation

### ISSUE THREAD

**Issue by EricNiedergang** [OFFLINE-GmbH/oc-boxes-support#5]
**Describe the bug**
Get on error when executing php artisan october:migrate after syncing project :

**Screenshots**
![image](https://user-images.githubusercontent.com/55832474/188099174-b7e327b4-1f5d-4873-8b4d-86db05fb06a7.png)

**Comment by EricNiedergang** [comment]
Tried to uninstall / reinstall properly, I also get this error. Forgot to report it before because I manually corrected it to be able to install

![image](https://user-images.githubusercontent.com/55832474/188101465-d4864fd4-0708-4fb9-adaf-a6926e4be85b.png)

I'm using SQLite, maybe it's important to consider

**Comment by tobias-kuendig** [comment]
This is looking like a SQLite issue, I will release a bugfix, thank you @EricNiedergang!

**Comment by tobias-kuendig** [comment]
This is fixed in v2.0.61. Let me know if you still experience any issues. Thank you for the report! :+1:
