### ISSUE TITLE
Installation failed - table does not exist

### ISSUE THREAD

**Issue by J-Brk** [OFFLINE-GmbH/oc-boxes-support#52]
**Describe the bug**
Fresh installation fails. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'olcg_dev.offline_boxes_pages' doesn't exist (SQL: select count(*) as aggregate from 'offline_boxes_pages' where 'published_state' = draft and 'published_at' is null and 'offline_boxes_pages'.'site_id' = 1 and ('offline_boxes_pages'.'theme' = americanprinter or 'offline_boxes_pages'.'theme' is null))" 

**Boxes Version**
unknown; latest available store version

**To Reproduce**
1. Purchase Boxes from the October store and add it to your project.
2. Within your project, navigate to project available plugins.
3. Click install "Boxes".
4. Installation error

**Additional context**
Latest OctoberCMS

**Comment by J-Brk** [comment]
It turns out it tries to add a `json` column type; which was not supported by the outdated MySQL (5.5/5.6). After upgrading the database the problem was resolved.

**Comment by tobias-kuendig** [comment]
Thank you for the report @J-Brk! MySQL 5.5 is out of support for more than a year. See https://en.wikipedia.org/wiki/MySQL

Using 5.7 is the way to go. I'll add a note about that to the docs.
