### ISSUE TITLE
Boxes not showing created in new theme's partials

### ISSUE THREAD

**Issue by AbdulSamaddestring** [OFFLINE-GmbH/oc-boxes-support#53]
**Describe the bug**

I created box with default theme to test, then I created a new theme on which i have to work on using simple october cms create theme option. but now if i create boxes partials in new theme they don't get listed.

**Boxes Version**

v 2.2.2

**To Reproduce**
1. create a test partial and test box yaml file
2. create a new theme
3. create actual box and try to view in admin > content  menu of boxes editor
4. new theme box will not be apearing.

I created it on october cms version 3.2.17
php version 8.0.24

**Comment by tobias-kuendig** [comment]
Just to be sure I understand your issue correctly:

1. You have created a Page with a Box
2. You switch the theme
3. You create a new Page with a new Box
4. The Box does not show up

It is important to understand that the partials (htm/yaml files) and the created Boxes (in the backend) are always stored per theme. So switching the theme gives you a clean slate. But if you create a new Box, it should then of course be visible.

Could you also check if the `theme` column in the `offline_boxes_pages` table is populated correctly?

**Comment by tobias-kuendig** [comment]
Also, please check if the problem still exists if you update to v2.2.3

**Comment by PubliAlex** [comment]
@AbdulSamaddestring I encoutered similar problem and I fixed it by defining the new theme in the .env file

**Comment by tobias-kuendig** [comment]
Thank you guys, I was able to reproduce the issue. It seems like `Theme::getActiveTheme()` does not return the active theme that is set in the backend but only the one from the `.env` file. I'll see if the issue is in Boxes or upstream and release a fix.

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig Appreciate your quick response and hope it will be fixed.
@patrick-durrer Great, your comment helped.

**Comment by tobias-kuendig** [comment]
Version `v2.2.5` has just been released that properly handles dynamic Site themes and changing the theme in the backend settings.
