### ISSUE TITLE
Can't give custom name to image or file type data box form fields

### ISSUE THREAD

**Issue by AbdulSamaddestring** [OFFLINE-GmbH/oc-boxes-support#56]
**Describe the bug**
I encountered an issue if I give a custom name to image form field in box yaml file it gives error

Model 'OFFLINE\Boxes\Models\Box' does not contain a definition for 'doctor_image'.

**Boxes Version**
v2.2.9

**To Reproduce**
1. create a partial and box yaml file
2. define image form field with a custom name other than image/file/images/files.
3. try to add box on the page

**Additional context**
if I want to use multiple different images on same box i have to modify boxes model every-time to include new name.

Hope it will get fixed.

**Comment by Andi-Moser** [comment]
Hi,

By default, the Box Model contains four relations: `image`, `images`, `file` and `files`.

It is not possible to add more images to a box without extending the Box Model as follows:

```php
class Provider extends AppBase
{
    public function boot()
    {
        \OFFLINE\Boxes\Models\Box::extend(function (Box $box) {
            $box->attachOne['doctor_image'] = File::class;
        });
    }
}
```

See [the documentation](https://docs.boxes.offline.ch/use-cases/relations.html) for reference.

Boxes uses the usual OctoberCMS concepts for extending file relations on models.

Have a nice day,

Andy
