### ISSUE TITLE
Global boxes

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#58]
# 💡 Do not post your feature request as an issue!

Hi! make it possible to create global boxes that can be used repeatedly on the site

![image](https://user-images.githubusercontent.com/40325840/230736684-d68ab590-7c77-4155-af96-62f51fd1735d.png)

![image](https://user-images.githubusercontent.com/40325840/230736857-7e9fe5f6-5c78-403b-84cd-ff70adeb6f55.png)

**Comment by tobias-kuendig** [comment]
@sellscompany thank you for this suggestion. We will ship "Box References" in version 3.0 in the coming weeks. 

Box references allow you to reference a box from another page. The docs for this feature are already written:
https://docs.boxes.offline.ch/concepts/box-references.html

Would that fit your use-case?

**Comment by sellscompany** [comment]
Thank you very much!
