### ISSUE TITLE
Increased editing space in modal

### ISSUE THREAD

**Issue by sellscompany** [OFFLINE-GmbH/oc-boxes-support#59]
It would be more convenient to have an increased editing space. But do not reduce the width of the site.

Example
![image](https://user-images.githubusercontent.com/40325840/231209506-94acccee-2346-4ac4-bdf4-31eaa11ad77b.png)

![image](https://user-images.githubusercontent.com/40325840/231210945-20525e3a-8324-4c87-abc1-3bdded864d7c.png)

**Comment by PubliAlex** [comment]
Agree, when the right sidebar form become complex (with repeater in builder mode etc...) things become quite unusable.

**Comment by tobias-kuendig** [comment]
This will be coming in version 3.0, see https://github.com/OFFLINE-GmbH/oc-boxes-support/discussions/66
