### ISSUE TITLE
Box References - can't find the tools partial

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#62]
Not sure if I am missing something obvious, but when I follow the docs to add a reference box, I cannot see the tools section mentioned.

I am running the latest versions of Boxes and OCMS

**Comment by tobias-kuendig** [comment]
@roojai, references are only available starting from Boxes version 3.0 which is currenly unreleased. We plan to release this version in the coming weeks.

**Comment by roojai** [comment]
ok, thanks for the clarification. When I saw the not about version 3 I wrongly assumed it referred to OCMS ver 3. 
Look forward to that release then!

**Comment by tobias-kuendig** [comment]
A beta version of this is now available for testing (but please don't use it in production just yet, see https://github.com/OFFLINE-GmbH/oc-boxes-support/discussions/66)
