### ISSUE TITLE
Updating post won't show data

### ISSUE THREAD

**Issue by mtareiling** [OFFLINE-GmbH/oc-boxes-support#65]
**Describe the bug**

When i create a post the data will be saved to the database, but when i edit the post it's not showing data. 
The iframe url constantly (every refresh) changes, i think this is the problem.
Iframe url: "/__boxes-preview/content/958"
I really don't know if i haven't configured something correctly or if this is a boxes bug.

**Boxes Version**
V2.2.12

**Code**
boxes.yaml:

<code>-   name: Newsletter
    handle: newsletter
    contexts:
    - newsletter
    boxes:
    - partial: newsletter-header
      locked: ['position', 'deletion']
    - partial: newsletter-text
    - partial: newsletter-image
</code>

Model:

    public $morphOne = [
        'newsletter_boxes' => [
            \CMS\Boxes\Models\Content::class,
            'name' => 'content'
        ]
    ];

Fields:

        newsletter_boxes:
            tab: cms.newsletter::lang.newsletter.newsletter_edit_section
            type: boxes
            span: adaptive
            cssClass: w-100
            previewLayout: newsletter_template
            template: newsletter
            partialContexts:
                - newsletter
            context: [create, update]

**Comment by tobias-kuendig** [comment]
>         \CMS\Boxes\Models\Content::class,

Just to be sure: Is this a typo or did you use a custom Content model (the default namespace would be `OFFLINE\Boxes\Models\Content::class`)? If so, what does it add?

**Comment by tobias-kuendig** [comment]
You have to make sure that you save the "parent" model as well. If you do this, the entry in the `offline_boxes_content` table should receive a `content_type` and `content_id`. The `is_pending_content` value should be switched from `1` to `0`.

Can you confirm that this works?

**Comment by mtareiling** [comment]
> > ```
> >     \CMS\Boxes\Models\Content::class,
> > ```
> 
> Just to be sure: Is this a typo or did you use a custom Content model (the default namespace would be `OFFLINE\Boxes\Models\Content::class`)? If so, what does it add?

This was indeed a typo. I was mistaking with our newsletter plugin.

> You have to make sure that you save the "parent" model as well. If you do this, the entry in the `offline_boxes_content` table should receive a `content_type` and `content_id`. The `is_pending_content` value should be switched from `1` to `0`.
> 
> Can you confirm that this works?

The `content_type` and `content_id` is set when creating the boxes content. For this entry `is_pending_content` is set to 0. However when we update the parent model. A new entry is created in the `offline_boxes_content` table with `content_id` and `content_type` is set to `NULL` and `is_pending_content` is set to 1. We will also investigate further at our side.

**Comment by tobias-kuendig** [comment]
To point you in the right direction. In the `BoxesEditor.php` form widget, the `Content` model is fetched/generated right at the top of the `init` method. If the `if (... !$this->resolveRelatedContentModel())` call does not return a model, it is created right inside that if statement.

Maybe check when this method is called and if the respective methods return the data that is expected.

The `Content` models are attached to the parent model using October's deferred bindings and the `is_pending_content` set to `true`. Once the parent model is saved, the `Content` is attached and the `is_pending_content` is set to `false`. From then on, that `Content` model should always be used and no new model should be created.
