### ISSUE TITLE
Duplicate box error

### ISSUE THREAD

**Issue by sikhub** [OFFLINE-GmbH/oc-boxes-support#67]
**Describe the bug**
When duplicating a box an error is thrown. After refreshing the page the box is there and can be edited and saved.
Boxes were exported locally and imported on production.

The error that is thrown: 
`"Attempt to read property "boxes" on null" on line 218 of /home/forge/{domain_name}/plugins/offline/boxes/formwidgets/BoxesEditor.php`

**Boxes Version**
v2.2.18

**To Reproduce**
1. Go to boxes content page
2. Click on duplicate the box
3. See error
4. Refresh the page
5. Box is there

**Screenshots**
<img width="1152" alt="Screenshot 2023-05-30 at 10 52 29" src="https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/4103737/b780c5b1-4af9-4ecc-b2ff-a2ceba7e6e4b">

Video:

[![Offline Boxes - Duplicate error](http://img.youtube.com/vi/o_Jb6vNDAzo/0.jpg)](http://www.youtube.com/watch?v=o_Jb6vNDAzo "Offline Boxes - Duplicate error")

https://www.youtube.com/watch?v=o_Jb6vNDAzo&ab_channel=sikmajnd

**Comment by tobias-kuendig** [comment]
Thank you very much for this detailed bug report @sikhub!

The bug is fixed in version v2.2.19
