### ISSUE TITLE
Version 3:  parent boxes acts as if it were the child in the editor.

### ISSUE THREAD

**Issue by roojai** [OFFLINE-GmbH/oc-boxes-support#69]
**Describe the bug**
Love the changes with V3. However a bug here:

After saving parent boxes with children in the editor, the parent boxes acts as if it were the child in the editor. That means, if you click on the parent box, it now displays the child's type in the purple bar at the top, and the editor on the right displays the content for the child. 
The parent box is still accessible if you click the parent box in the structure layout on the left, just not in the central content display. 

Images provided to illustrate:

**Before Version 3: **

CHILD box is "Content Column"

![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/31172173/ad0b08df-e569-4f06-9d87-080e6eafaf4b)

Click outside child to access PARENT box which is then editable
![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/31172173/f058a4f5-2a0f-4ff9-81b0-80a176de703c)

**After Version 3**
![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/31172173/9066d628-e95a-4566-9285-98d373967a50)

![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/31172173/7ff741f2-61c6-4c92-b77b-6197246c0519)

**Comment by tobias-kuendig** [comment]
@roojai, thank you for this report! Do you mind sharing the code you use to render the children of the `section` box?

**Comment by tobias-kuendig** [comment]
Nevermind, I was able to reproduce the issue. I'm working on a fix.

**Comment by tobias-kuendig** [comment]
@roojai Can you check if the bug is solved for you in v3.0.10?

**Comment by roojai** [comment]
Thanks @tobias-kuendig - yes the update fixed it!

**Comment by tobias-kuendig** [comment]
Great, thank you for the report!
