### ISSUE TITLE
A record does not exist for the selected site. Create one? Not working...

### ISSUE THREAD

**Issue by tecnotrade** [OFFLINE-GmbH/oc-boxes-support#70]
**Describe the bug**
Thanks for your work guys, it's really great!
We've builded tons of blocks and using them daily.

**Boxes Version**
3.0.10

When I switch to secondary site I can see the messagge to create a record, clicking OK OCMS switches the site but I can't see any new page on the left sidebar. What am I missing?
Thanks in advance!

**Comment by tobias-kuendig** [comment]
Thank you for the report @tecnotrade! There was an issue with the site switcher's action. When you first visited the Editor, no page ID was present in the URL, so Boxes did not know which page to copy when switching sites.

This issue has been solved in v3.0.11.
