### ISSUE TITLE
offline.boxes.editorRefreshed JS event not triggered when you delete a box

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-boxes-support#73]
**Describe the bug**
When you delete a box, the offline.boxes.editorRefreshed JS event is not triggered.

**Boxes Version**
v3.0.11

**To Reproduce**
Create a box partial with that script : 
```
    <script>
        window.document.addEventListener('offline.boxes.editorRefreshed', function (e) {
            console.log('The editor was refreshed');
        });
    </script>
```
When you add a new box or change box order, the event is correctly triggered, but not when you delete a box.

**Comment by tobias-kuendig** [comment]
Thank you for the report! This is fixed in v3.1.
