### ISSUE TITLE
Small error with og:locale

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#74]
Hello,

I noticed a small error in the seo.htm partial

The og:locale tag content should display language in language_TERRITORY format.

So it should be en_US, fr_FR, etc... instead of just the country code.

Best regards,

**Comment by tobias-kuendig** [comment]
Good catch! Unfortunately, we do not have the territory information about the page. Ideally, October would store it with each Site, but there only the two character locale code is stored.

**Comment by tobias-kuendig** [comment]
I'm closing this as won't fix because the territory information is ideally added in October core.
