### ISSUE TITLE
Wrong box overlay calculation

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#8]
**Describe the bug**
When using admin panel of boxes, all boxes overlay are higher than their respective boxes.
It's annoying because this overlay goes over the box which is below, misleading the user about the perimeter of the box

**Screenshots**
You can see in the screenshot that I hover the HTML element that have data-boxes-container attribute.
I circled in red the extra height added by boxes overlay

![image](https://user-images.githubusercontent.com/55833027/188478147-b973d3be-7ac8-4001-a077-249a011b6a52.png)

**Comment by PubliAlex** [comment]
Found the problem, it's in offline/boxes/assets/js/offline.boxes.editor.js

Line 57, you have an hardcoded value of padding : 
    padding = 100;

Cound not understand why you added a padding of 100 here, setting value to 0 and the box overlay is just fine (just fit the data-boxes-container element which is what you want to do in most cases).

Best regards,

**Comment by tobias-kuendig** [comment]
Thank you for your feedback, @PubliAlex. This is actually done on purpose. The padding is used to enlarge the padding a bit on both sides, since without the padding, the focus can overlap the content in some cases.

I'll see what we can do to improve this.

**Comment by PubliAlex** [comment]
Thank you for your answer, to fit most cases, maybe that padding could be setup by box, like you already do with the container attribute "data-boxes-container"

You could use something like this : data-boxes-padding="XXX", or still keep the same attribute because data-boxes-container don't need values actually, the value you set here could be the value of the padding you want : data-boxes-container="100"

Best regards,

**Comment by tobias-kuendig** [comment]
Great suggestion! I have implemented that in v2.0.60 (the default padding has been removed).

Docs: https://docs.boxes.offline.ch/concepts/box-editor.html#container-detection
