### ISSUE TITLE
Configuration in the same file than view

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#80]
Hello,

This is an idea that came to my mind, that would allow to resolve the issue to integrate box configuration directly in the october cms editor.

Why not integrate the box configuration, the yaml file, directly to the partial. It would be more inline with the october way of doing thing, when you look in an october page file, you have the configuration on the top of the file, then php code then the html, all separated with ==. Boxes could be configured using the same paradigm, it would be easier to create / edit boxes as you have only one file to open, and maybe, if the editor allow this, we could have 2 tabs in the editor IDE, one to edit the view, one to edit the configuration, exactly like the php tab we have to add some code to an october cms page or partial ?

What do you think about this ?

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Experimental support for this has landed in v3.2: https://docs.boxes.offline.ch/concepts/box-configs.html#defining-the-box-config-inline

**Comment by PubliAlex** [comment]
Hello, wonderful news !
