### ISSUE TITLE
Why we can't upload svg image

### ISSUE THREAD

**Issue by shoaibsohoby** [OFFLINE-GmbH/oc-boxes-support#81]
**Describe the bug**

**Boxes Version**
v2.x.y

**To Reproduce**
[
![Editor _ October CMS (2)](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/135807192/499ae1a5-87b4-431c-9a3f-6a19e7c2890a)
](url)

**Comment by tobias-kuendig** [comment]
Can you upload SVGs in a different plugin? Boxes does not limit the file types you can upload, this is a CMS wide setting in October.

**Comment by shoaibsohoby** [comment]
> Can you upload SVGs in a different plugin? Boxes does not limit the file types you can upload, this is a CMS wide setting in October.

yes I can upload svg to different plugin

**Comment by shoaibsohoby** [comment]
yes I can upload svg to different plugin
On Sun, 2023-07-09 at 23:07 -0700, Tobias Kündig wrote:
> Can you upload SVGs in a different plugin? Boxes does not limit the
> file types you can upload, this is a CMS wide setting in October.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 

Shoaib Hussain
Back-end Developer
Engineering Team | Sohoby


***@***.***://sohoby.comaddressJeddah,
Riyadh, Multan

**Comment by AbdulSamaddestring** [comment]
@tobias-kuendig any update on it.

**Comment by tobias-kuendig** [comment]
October does not allow SVG files for image uploads by default. To fix this issue either set the mode of the file upload explicitly to `file`:

```yaml
        image:
            type: fileupload
            mode: file            # this is important
```

or allow `svg` files as images by adding this to your `config/cms.php`:

```php
    // Allow additional file extensions to be uploaded.
    'file_definitions' => [
        'image_extensions' => [
            'jpg',
            'jpeg',
            'bmp',
            'png',
            'webp',
            'gif',
            'svg',
        ]
    ]
```
