### ISSUE TITLE
Boxes located in parent theme not showing

### ISSUE THREAD

**Issue by kevin-invato** [OFFLINE-GmbH/oc-boxes-support#82]
Hi! I found a small bug in the plugin: 

When you use a child theme, the boxes in the parent theme partial folder are not showing up in the boxes editor. The partials must be copied to the child theme to be used.

**Boxes Version**
v3^

**To Reproduce**
1. Create empty theme and set parent theme to your main theme
2. Go to the boxes editor
3. No boxes showing up :-(

A bit extra content why we want to use this:

We're building a "starter-theme" for our clients, and we want to be able to push updates to this theme so we don't have to do it manually to every client who uses the theme. So we came up with the idea to use child themes that basically only has a different tailwind config and some component overrides. Unfortunately this doesn't work right now because the updates won't affect the child themes.

I hope this is easy to fix, if you need any more info, please let me know :-)

Thanks in advance,

- Kevin

**Comment by tobias-kuendig** [comment]
Thank you for this report. Child themes is something we have not used in our projects. The Partial reader class currently is only looking in the default themes/x/partials folder for boxes.

I have added an issue to our internal tracker to implement child theme support.

**Comment by gldrenthe89** [comment]
Hi @tobias-kuendig is there any update on this?

**Comment by tobias-kuendig** [comment]
Implemented in v3.3.1, let me know how it works for you!

**Comment by RitsmG** [comment]
@tobias-kuendig 

The changes made for this issue resulted in some additional issues. 
We had a lot of issues with duplicate handles for various sites because Yaml files are not overwritten in the current implementation.

Could it be changed so either the yaml files are also overwritten by the child files?

**Comment by tobias-kuendig** [comment]
@RitsmG Do i get this right, you have yaml files with the same handle in the parent and child theme and this is currently throwing an error?

**Comment by RitsmG** [comment]
@tobias-kuendig This is correct.

**Comment by tobias-kuendig** [comment]
@RitsmG please give v3.3.13 a try and let me know how it works for you.
