### ISSUE TITLE
Sorting is ignored in editor.

### ISSUE THREAD

**Issue by robinbonnes** [OFFLINE-GmbH/oc-boxes-support#83]
**Describe the bug**
When dragging a page down or up, after refresh the sorting is still in it's original state.

**Boxes Version**
v3.1.12

**To Reproduce**
1. Go to Editor
2. Drag a page up/down in the page structure.
3. Refresh page
4. Sorting didn't change.

**Code**
Found it actually does change the `nest_left` and `nest_right` column, however sorting isn't applied in the editor. It needs something like the following in the formwidget `BoxesEditor.php` `buildState` function:

```$pages = $this->isFullMode() ? Page::currentDrafts()->orderBy('nest_right')->get()->toNested(false) : collect([]);```

**Comment by tobias-kuendig** [comment]
Thank you very much @robinbonnes for this great report and providing the actual fix :upside_down_face: 

Version v3.1.14 solves this issue.
