### ISSUE TITLE
On duplicated pages, boxes keep (some) references to their original instances

### ISSUE THREAD

**Issue by elisandroesp** [OFFLINE-GmbH/oc-boxes-support#85]
**Describe the bug**
Elements on duplicated pages keep weird references to their original elements.

**Boxes Version**
v3.1.17

**To Reproduce**
1. Truncate all boxes DB tables
2. Create a page, call it Page1
3. Insert 2 boxes, call them A and B
4. Duplicate the page (Page2)
5. On Page2,  move box A down, to be after B
6. Go to Page1, they will have switched there too, no matter if you force refresh the page, it's on the database

**Code**
Paste any relevant code samples (Box config, partial) here.

**Screenshots**

**Additional context**

**Comment by tobias-kuendig** [comment]
Thank you for this detailed report @elisandroesp!

This bug has been resolved in v3.1.19. The nested tree query was not scoped to the current page, so the query updated the order of all Boxes with the same tree position (which the original and dupliated Boxes shared).

**Comment by elisandroesp** [comment]
Thanks for the explanation!
Boxes is really the missing piece for October, we love it!
