### ISSUE TITLE
A node cannot be moved to a descendant of itself

### ISSUE THREAD

**Issue by tecnotrade** [OFFLINE-GmbH/oc-boxes-support#88]
Hello,
we've written many block to use with your great plugin but now we've a strange issue.
Moving a box from the left column above or bottom another we've got this message:

"A node cannot be moved to a descendant of itself." on line 990 of
....../traits/nestedtress.php

There's no parent/child box anywhere.

How can we fix that?

**Comment by tobias-kuendig** [comment]
Are you using the latest version of Boxes? We have integrated a bugfix for this problem in the latest version. If it is not solved for you, let me know.

**Comment by tecnotrade** [comment]
Thankyou, just updated to 3.1.19 (didn’t see that bugfix!) but still having the issue.
Is there some sort of cache I could clean in it?

SIMONE RESCA
Digital Advisor
tecnotrade | TECNOLOGIA & STRATEGIA
 
E ***@***.*** ***@***.***> | W https://tecnotrade.com <http://www.tecnotrade.com/> | T 051 19870779 | M 348.2616422 


Avvertenza: la presente casella e-mail ed i messaggi da essa derivanti, sono di esclusivo utilizzo aziendale/lavorativo e mai personale. Risposte al presente messaggio: si avvisa il destinatario che eventuali sue risposte potranno essere lette dall’intera azienda/ufficio/reparto di appartenenza del mittente. Se per un disguido avete ricevuto questa e-mail senza esserne i destinatari vogliate cortesemente distruggerla e darne informazione all’indirizzo mittente inviando una mail a ***@***.*** ***@***.***>

**Comment by tobias-kuendig** [comment]
It sounds like your tree structure is damaged. Could you update to the latest version v3.1.20 and run the following command against a test database?

```shell
php artisan boxes:heal-tree 
```

This will rebuild the page tree structure. After running the command your pages should be sorted the same way as before. Drag and drop should now be working.

Please let me know if the problem persists.

**Comment by tecnotrade** [comment]
Great job guys, you're the best. It works like a charme!!!

**Comment by tobias-kuendig** [comment]
Great to hear, thank you for reporting the issue @tecnotrade!
