### ISSUE TITLE
Error updating boxes

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#89]
**Describe the bug**
Hello

I tried to update boxes to the latest version to test the new "all in one file" feature, but get an error in the console : 

> In Container.php line 891:
>                                                                             
>  Target class [OFFLINE\Boxes\Console\HealBoxesTreeCommand] does not exist.  
>                                                                             
>
>In Container.php line 889:
>                                                                     
>  Class "OFFLINE\Boxes\Console\HealBoxesTreeCommand" does not exist  
>                                                                     
>
>105 packages you are using are looking for funding.
>Use the `composer fund` command to find out more!
> System\Console\ComposerScript::postUpdateCmd
>
>In Container.php line 891:
>                                                                             
>  Target class [OFFLINE\Boxes\Console\HealBoxesTreeCommand] does not exist.  
>                                                                            
>
>In Container.php line 889:
>                                                                     
>  Class "OFFLINE\Boxes\Console\HealBoxesTreeCommand" does not exist  
>                                                                     
>
>
>In Container.php line 891:
>                                                                             
>  Target class [OFFLINE\Boxes\Console\HealBoxesTreeCommand] does not exist.  
>                                                                             
>
>In Container.php line 889:
>                                                                     
>  Class "OFFLINE\Boxes\Console\HealBoxesTreeCommand" does not exist  

Best regards

**Comment by tobias-kuendig** [comment]
Thank you for the report @PubliAlex. This was an error in the free release of Boxes, please try the latest version v3.2.3 where this should work now.

**Comment by PubliAlex** [comment]
Confirmed it works, to make the update, I had to use composer update instead of php artisan october update that still bring me an error. After the composer update, the php artisan october update worked fine
