### ISSUE TITLE
Parent pages (including revisions) show in submenu

### ISSUE THREAD

**Issue by RitsmG** [OFFLINE-GmbH/oc-boxes-support#92]
For a site for a client of mine we have a set of boxes pages. One of which has a coupe of childpages. We use the rainlab static pages plugin for creating menu's on the website.

When creating a menu item which has the parent page reference. When selecting "Allow nested items" to show the child pages as a sub menu. The sub menu on the main page shows the parent page including all its revisions.

**Boxes Version**
v3.3.4

**Comment by tobias-kuendig** [comment]
@RitsmG, thank you for this report! Please give v3.3.7 a try and let me know if the issue is not fixed for you.
