### ISSUE TITLE
Not working plugin

### ISSUE THREAD

**Issue by r-revel** [OFFLINE-GmbH/oc-boxes-support#93]
**Describe the bug**

We're sorry, but an unhandled error occurred. Please see the details below.
Call to undefined method OFFLINE\Boxes\Classes\Partial\PartialReader::handleThemePartialsDir()

**Boxes Version**
v3.3.7

**To Reproduce**

Open backend menu ./backend/offline/boxes/editorcontroller

**Comment by tobias-kuendig** [comment]
Thank you for the report, please give v3.3.9 a try.
