### ISSUE TITLE
Invalid filename when using the reference box

### ISSUE THREAD

**Issue by RitsmG** [OFFLINE-GmbH/oc-boxes-support#94]
When using a reference box we get the following error:

An exception has been thrown during the rendering of a template ("Invalid file name: */plugins/offline/boxes/views/partials/reference.htm. File names may only contain letters, numbers, underscores, dashes and periods. Examples of correct file names: page.htm, page, folder/page").

We have tested this on multiple installations and we get this error on all of them. The original box does show correctly.

**Boxes Version**
v3.3.4

**Comment by tobias-kuendig** [comment]
Thank you for reporting this, please give version 3.3.12 a try and let me know if the problem still exists.
