### ISSUE TITLE
Meta Keywords input needed

### ISSUE THREAD

**Issue by tecnotrade** [OFFLINE-GmbH/oc-boxes-support#96]
Hi Guys, any plan to add keyword input text in page section for a better SEO?

**Comment by tobias-kuendig** [comment]
Where would you use these keywords? The keywords meta tag has been "dead" for years now (no search engine cares about it). Do you have any other use-cases for it?

**Comment by tecnotrade** [comment]
You're right Tobias, that's the official version, but many tools (SeoZoom, UberSuggest from Neil Patel,...) are still indicating that missing in boxes pages as a mistake. Don't know how to override that...

**Comment by tobias-kuendig** [comment]
Did you see that you can add custom fields to the page form relatively easy? Would that be a solution for you?

https://docs.boxes.offline.ch/use-cases/page-specific-data.html

**Comment by tecnotrade** [comment]
Didn't see that, sorry, I'll try to implement that in this way.
Thanks again
