### ISSUE TITLE
Cannot change standalone image field title or description

### ISSUE THREAD

**Issue by viktor-nemeth** [OFFLINE-GmbH/oc-boxes-support#98]
**Describe the bug**
Cannot change standalone image field title or description

**Boxes Version**
v3.3.16

**To Reproduce**
1. create standalone fileupload (image) field
2. create boxes content field
3. upload an image to a standalone image field
4. try to change this uploaded image title or description.

**Screenshots**
![Image-2024-01-03 13_44_11](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/61492806/e1a413e2-feab-481b-9ff1-062257a6ed96)

**Comment by tobias-kuendig** [comment]
@viktor-nemeth please give v3.3.17 a try, this issue should be fixed there.

Thank you for the report!
